// Generated by ClaudeCode
'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import DeskScientist from '@/components/illustrations/DeskScientist'
import { MailIcon } from '@/components/icons/CommonIcons'

export default function CTASection() {
  return (
    <section className="section-padding relative bg-white overflow-hidden" id="cta">
      {/* Decorative background */}
      <div className="absolute inset-0 dot-pattern opacity-20" />

      <div className="container-custom relative z-10">
        {/* Section Label */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-sm font-mono text-accent border-l-4 border-accent pl-4 mb-8"
        >
          #07 CONTACT US
        </motion.div>

        <div className="grid lg:grid-cols-2 gap-16 items-center">
          {/* Text Content */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="space-y-8"
          >
            <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold leading-tight">
              あなたの
              <br />
              <span className="text-accent">&quot;研究テーマ&quot;</span>を
              <br />
              教えてください。
            </h2>

            <div className="space-y-4 text-lg leading-relaxed text-foreground/90">
              <p>
                「この作業を自動化したい」
                <br />
                「このフローを簡略化したい」
              </p>

              <p className="font-bold">
                まずは1テーマから、
                <br />
                実験を始めましょう。
              </p>
            </div>

            {/* Contact Methods */}
            <div className="space-y-4 pt-4">
              <Link href="/contact">
                <motion.div
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  className="inline-block w-full md:w-auto bg-accent hover:bg-accent/90 text-white font-bold px-10 py-5 rounded-lg transition-all duration-300 border-2 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] text-center cursor-pointer"
                >
                  無料相談フォームへ →
                </motion.div>
              </Link>

              <div className="flex items-center space-x-4 text-sm text-foreground/70 pt-2">
                <span className="flex items-center space-x-2">
                  <MailIcon className="text-accent" />
                  <span>フォームからお問い合わせください</span>
                </span>
              </div>
            </div>

            {/* Trust indicators */}
            <div className="grid grid-cols-3 gap-4 pt-8 border-t-2 border-black/10">
              <div className="text-center">
                <div className="text-3xl font-bold text-accent">50+</div>
                <div className="text-xs text-foreground/70 mt-1">プロジェクト</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-accent">30+</div>
                <div className="text-xs text-foreground/70 mt-1">企業導入</div>
              </div>
              <div className="text-center">
                <div className="text-3xl font-bold text-accent">98%</div>
                <div className="text-xs text-foreground/70 mt-1">満足度</div>
              </div>
            </div>
          </motion.div>

          {/* Illustration */}
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="relative"
          >
            <div className="bg-background p-8 rounded-2xl border-2 border-black shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
              <DeskScientist />
            </div>

            {/* Floating speech bubble */}
            <motion.div
              className="absolute -top-8 -right-8 bg-white border-2 border-black px-6 py-3 rounded-2xl shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] max-w-[200px]"
              animate={{
                y: [0, -10, 0],
              }}
              transition={{
                duration: 3,
                repeat: Infinity,
                ease: 'easeInOut',
              }}
            >
              <p className="text-sm font-bold">実験、始めましょう！</p>
              <div className="absolute -bottom-3 left-8 w-0 h-0 border-l-[12px] border-l-transparent border-r-[12px] border-r-transparent border-t-[12px] border-t-black" />
              <div className="absolute -bottom-[10px] left-[9px] w-0 h-0 border-l-[10px] border-l-transparent border-r-[10px] border-r-transparent border-t-[10px] border-t-white" />
            </motion.div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
