// Generated by ClaudeCode
'use client'

import { motion } from 'framer-motion'
import { ListenIcon, DesignIcon, DeployIcon, MaintenanceIcon } from '@/components/icons/FlowIcons'

const steps = [
  {
    number: '01',
    Icon: ListenIcon,
    title: 'ヒアリング',
    description: 'お客様の課題や業務フローを詳しくヒアリング。本質的な課題を特定します。',
  },
  {
    number: '02',
    Icon: DesignIcon,
    title: '設計・試作',
    description: '最適な技術スタックを選定し、プロトタイプを素早く構築。実際に触って検証できます。',
  },
  {
    number: '03',
    Icon: DeployIcon,
    title: '納品・導入',
    description: 'システムを納品し、使い方をレクチャー。スムーズに業務へ導入できるようサポートします。',
  },
  {
    number: '04',
    Icon: MaintenanceIcon,
    title: '保守・改善',
    description: '運用後の課題に対応し、継続的に改善。ビジネスの変化に合わせてアップデートします。',
  },
]

export default function FlowSection() {
  return (
    <section className="section-padding relative overflow-hidden" id="flow">
      {/* Background decorations */}
      <div className="absolute inset-0 grid-pattern opacity-20" />

      <div className="container-custom relative z-10">
        {/* Section Label */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-sm font-mono text-accent border-l-4 border-accent pl-4 mb-8"
        >
          #06 DEVELOPMENT PROCESS
        </motion.div>

        {/* Title */}
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-4xl md:text-5xl font-bold mb-16 text-center"
        >
          開発の<span className="text-accent">流れ</span>
        </motion.h2>

        {/* Flow Steps */}
        <div className="max-w-5xl mx-auto">
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((step, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: 0.2 + index * 0.1 }}
                className="relative"
              >
                {/* Connection Line (hidden on last item) */}
                {index < steps.length - 1 && (
                  <div className="hidden lg:block absolute top-16 -right-4 w-8 h-0.5 bg-accent z-0">
                    <motion.div
                      className="h-full bg-accent"
                      initial={{ scaleX: 0 }}
                      whileInView={{ scaleX: 1 }}
                      viewport={{ once: true }}
                      transition={{ duration: 0.8, delay: 0.5 + index * 0.2 }}
                    />
                  </div>
                )}

                {/* Step Card */}
                <div className="bg-white border-2 border-black rounded-xl p-6 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-2 transition-all duration-300 relative z-10 h-full">
                  {/* Step Number Badge */}
                  <motion.div
                    initial={{ scale: 0, rotate: -180 }}
                    whileInView={{ scale: 1, rotate: 0 }}
                    viewport={{ once: true }}
                    transition={{
                      type: 'spring',
                      stiffness: 200,
                      delay: 0.3 + index * 0.1,
                    }}
                    className="inline-block bg-accent text-white font-mono font-bold text-sm px-3 py-1 rounded-full border-2 border-black mb-4"
                  >
                    STEP {step.number}
                  </motion.div>

                  {/* Icon */}
                  <motion.div
                    initial={{ scale: 0, rotate: -180 }}
                    whileInView={{ scale: 1, rotate: 0 }}
                    viewport={{ once: true }}
                    transition={{
                      type: 'spring',
                      stiffness: 150,
                      delay: 0.4 + index * 0.1,
                    }}
                    className="mb-6 flex justify-center"
                  >
                    <step.Icon className="w-20 h-20" />
                  </motion.div>

                  {/* Title */}
                  <h3 className="text-xl font-bold mb-3">{step.title}</h3>

                  {/* Description */}
                  <p className="text-sm text-foreground/80 leading-relaxed">
                    {step.description}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}
