// Generated by ClaudeCode
'use client'

import { motion } from 'framer-motion'
import { BeakerIcon, MailIcon, LocationIcon, ClockIcon } from '@/components/icons/CommonIcons'

export default function Footer() {
  const currentYear = new Date().getFullYear()

  return (
    <footer className="bg-black text-white border-t border-[#333] py-12 relative overflow-hidden">
      {/* Background Grid Pattern */}
      <div className="absolute inset-0 opacity-5 pointer-events-none">
        <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <pattern id="footer-grid" width="40" height="40" patternUnits="userSpaceOnUse">
              <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#footer-grid)" />
        </svg>
      </div>

      {/* Scan Line Effect */}
      <motion.div
        className="absolute inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/3 to-transparent pointer-events-none"
        animate={{ y: ['-100%', '200%'] }}
        transition={{ duration: 10, repeat: Infinity, ease: 'linear' }}
      />

      <div className="container-custom relative z-10">
        <div className="grid md:grid-cols-3 gap-12 mb-8">
          {/* Brand */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="border-l-2 border-[#78C4D4] pl-4"
          >
            <h3 className="font-mono text-xl font-bold mb-4 flex items-center space-x-2">
              <BeakerIcon className="text-yellow-400 w-7 h-7" size={28} />
              <span className="text-[#78C4D4]">3125_LAB</span>
              <span className="text-yellow-400 text-sm animate-pulse">⚠</span>
            </h3>
            <p className="font-mono text-xs text-white/70 leading-relaxed">
              {'// '}業務課題を、実験で仕組みに変える研究所。
              <br />
              {'// '}ニッチな業務課題を実験的に解決します。
            </p>

            {/* System Status */}
            <div className="mt-4 pt-4 border-t border-[#333]">
              <div className="font-mono text-xs text-white/50 space-y-1">
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 bg-yellow-400 rounded-full animate-pulse"></span>
                  <span>SYSTEM: <span className="text-yellow-400">CRITICAL</span></span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-yellow-400">⚠</span>
                  <span>VERSION: <span className="text-[#78C4D4]">v2.0.0</span></span>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Quick Links */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="border-2 border-yellow-600/50 p-6 bg-black/50 shadow-[0_0_10px_rgba(234,179,8,0.2)]"
          >
            <h4 className="font-mono font-bold mb-4 text-yellow-400 text-sm uppercase tracking-wider flex items-center gap-2">
              <span className="animate-pulse">⚠</span>
              [NAVIGATION]
              <span className="animate-pulse">⚠</span>
            </h4>
            <ul className="space-y-2 font-mono text-xs">
              {[
                { label: 'TOP', href: '/', warning: true },
                { label: 'WORKS', href: '/works', warning: false },
                { label: 'CONTACT', href: '/contact', warning: true },
                { label: 'PROBLEM', href: '/#problem', warning: false },
                { label: 'SOLUTION', href: '/#solution', warning: false },
                { label: 'SERVICE', href: '/#service', warning: true },
                { label: 'FLOW', href: '/#flow', warning: false },
              ].map((link, index) => (
                <li key={index}>
                  <a
                    href={link.href}
                    className="text-white/60 hover:text-yellow-400 transition-colors duration-300 flex items-center gap-2 group"
                  >
                    <span className="text-[#78C4D4] group-hover:text-yellow-400">{'>'}</span>
                    <span>{link.label}</span>
                    {link.warning && (
                      <span className="text-yellow-400 text-[10px] opacity-50 group-hover:opacity-100">⚠</span>
                    )}
                  </a>
                </li>
              ))}
            </ul>
          </motion.div>

          {/* Contact Info */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="border-2 border-red-600/50 p-6 bg-black/50 relative overflow-hidden shadow-[0_0_15px_rgba(220,38,38,0.3)]"
          >
            {/* Corner brackets */}
            <div className="absolute top-0 left-0 w-4 h-4 border-t-2 border-l-2 border-yellow-400" />
            <div className="absolute top-0 right-0 w-4 h-4 border-t-2 border-r-2 border-yellow-400" />
            <div className="absolute bottom-0 left-0 w-4 h-4 border-b-2 border-l-2 border-yellow-400" />
            <div className="absolute bottom-0 right-0 w-4 h-4 border-b-2 border-r-2 border-yellow-400" />

            {/* Pulsing warning background */}
            <motion.div
              className="absolute inset-0 bg-yellow-400/5"
              animate={{ opacity: [0.05, 0.15, 0.05] }}
              transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
            />

            <h4 className="font-mono font-bold mb-4 text-yellow-400 text-sm uppercase tracking-wider relative z-10 flex items-center gap-2">
              <span className="animate-pulse">⚠</span>
              [CONTACT_INFO]
              <span className="animate-pulse">⚠</span>
            </h4>
            <ul className="space-y-3 font-mono text-xs relative z-10">
              <li className="flex items-start space-x-3">
                <LocationIcon className="text-yellow-400 flex-shrink-0 mt-0.5" />
                <span className="text-white/70">
                  {'> '}東京都渋谷区
                  <br />
                  <span className="text-white/50 text-[10px]">{'  // '}オンライン対応可</span>
                </span>
              </li>
              <li className="flex items-start space-x-3">
                <ClockIcon className="text-yellow-400 flex-shrink-0 mt-0.5" />
                <span className="text-white/70">
                  {'> '}平日 10:00-18:00
                </span>
              </li>
            </ul>

            {/* Status Badge */}
            <div className="mt-4 pt-4 border-t border-yellow-600/30 relative z-10">
              <div className="inline-flex items-center gap-2 px-3 py-1 bg-yellow-400/20 border-2 border-yellow-400/50">
                <span className="w-2 h-2 bg-yellow-400 rounded-full animate-pulse"></span>
                <span className="font-mono text-[10px] text-yellow-400 font-bold">URGENT_CONTACT_AVAILABLE</span>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Divider */}
        <div className="border-t-2 border-yellow-600/30 my-8 relative">
          <motion.div
            className="absolute inset-0 bg-gradient-to-r from-transparent via-yellow-400/30 to-transparent"
            animate={{ x: ['-100%', '200%'] }}
            transition={{ duration: 3, repeat: Infinity, ease: 'linear' }}
          />
          {/* Warning stripes */}
          <div className="absolute inset-0 flex gap-4 overflow-hidden opacity-10">
            {[...Array(20)].map((_, i) => (
              <div key={i} className="w-2 h-full bg-yellow-400 transform -skew-x-12" />
            ))}
          </div>
        </div>

        {/* Bottom Bar */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0 font-mono text-xs text-white/50"
        >
          <div className="flex items-center gap-2">
            <span className="text-yellow-400 animate-pulse">⚠</span>
            <p>
              {'© '}{currentYear} 3125_LAB <span className="text-yellow-400">|</span> All Rights Reserved
            </p>
            <span className="text-yellow-400 animate-pulse">⚠</span>
          </div>

          <div className="flex space-x-6">
            <a
              href="#"
              className="hover:text-yellow-400 transition-colors duration-300 uppercase tracking-wider flex items-center gap-1"
            >
              <span className="text-yellow-400 text-[10px]">⚠</span>
              {'[ '}Privacy{' ]'}
            </a>
            <a
              href="#"
              className="hover:text-yellow-400 transition-colors duration-300 uppercase tracking-wider flex items-center gap-1"
            >
              <span className="text-yellow-400 text-[10px]">⚠</span>
              {'[ '}Terms{' ]'}
            </a>
          </div>
        </motion.div>

        {/* Lab Badge */}
        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.5 }}
          className="text-center mt-8 pt-8 border-t border-[#333] relative"
        >
          <motion.div
            className="absolute inset-0 bg-gradient-to-r from-transparent via-[#00FF96]/5 to-transparent"
            animate={{ x: ['-100%', '200%'] }}
            transition={{ duration: 6, repeat: Infinity, ease: 'linear' }}
          />
          <div className="inline-flex items-center gap-2 bg-[#00FF96]/10 border border-[#00FF96]/30 px-6 py-2 relative">
            <span className="w-2 h-2 bg-[#00FF96] rounded-full animate-pulse"></span>
            <span className="text-[#00FF96] font-mono text-xs uppercase tracking-wider">
              LAB_STATUS: ACTIVE
            </span>
          </div>
        </motion.div>
      </div>
    </footer>
  )
}
