// Generated by ClaudeCode - Control Panel Style Header
'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useState, useEffect } from 'react'

export default function Header() {
  const pathname = usePathname()
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const [experiments, setExperiments] = useState(12)

  // Navigation items
  const navItems = [
    { label: 'RESEARCH', href: '/research' },
    { label: 'WORKS', href: '/works' },
    { label: 'SYSTEMS', href: '/systems' },
    { label: 'CONTACT', href: '/contact' },
  ]

  // Scroll detection for header height change
  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 50)
    }
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  // Pseudo experiment counter animation
  useEffect(() => {
    const interval = setInterval(() => {
      setExperiments(prev => {
        const change = Math.random() > 0.5 ? 1 : -1
        const newVal = prev + change
        return Math.max(9, Math.min(13, newVal))
      })
    }, 2000)
    return () => clearInterval(interval)
  }, [])

  // Determine active tab based on current location
  const getActiveTab = () => {
    if (pathname === '/contact') return 'CONTACT'
    if (pathname === '/works') return 'WORKS'
    if (pathname === '/systems') return 'SYSTEMS'
    if (pathname === '/research') return 'RESEARCH'
    // No active tab for home page
    return null
  }

  const activeTab = getActiveTab()

  return (
    <header
      className={`fixed w-full z-50 top-0 bg-black/95 backdrop-blur-sm border-b border-[#333] transition-all duration-300 ease-out ${
        scrolled ? 'h-16' : 'h-20'
      }`}
    >
      {/* Background Grid Pattern (SVG) */}
      <div className="absolute inset-0 opacity-10 pointer-events-none">
        <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse">
              <path d="M 20 0 L 0 0 0 20" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
            </pattern>
            <pattern id="dots" width="4" height="4" patternUnits="userSpaceOnUse">
              <circle cx="2" cy="2" r="0.5" fill="#78C4D4"/>
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#grid)" />
          <rect width="100%" height="100%" fill="url(#dots)" opacity="0.3" />
        </svg>
      </div>

      <div className="container mx-auto px-4 h-full flex items-center justify-between relative z-10">

        {/* Left: Brand Logo */}
        <Link href="/" className="flex flex-col group">
          <motion.div
            whileHover={{ textShadow: '0 0 8px rgba(120, 196, 212, 0.8)' }}
            className="font-mono text-white text-lg md:text-xl tracking-tight uppercase transition-all duration-300"
          >
            {'<'}3125_LAB{'>'}
          </motion.div>
          <div className="font-mono text-[10px] text-[#78C4D4] tracking-widest opacity-70 group-hover:opacity-100 transition-opacity">
            AI × SYSTEM R&D
          </div>
        </Link>

        {/* Center: Navigation Tabs (Desktop) */}
        <nav className="hidden lg:flex items-center space-x-2">
          {navItems.map((item) => {
            const isActive = activeTab === item.label

            return (
              <Link
                key={item.label}
                href={item.href}
                className="relative"
              >
                <motion.div
                  whileHover={{ scale: 1.05 }}
                  className={`
                    font-mono text-xs px-4 py-2 border border-[#333]
                    transition-all duration-300 uppercase tracking-wider
                    ${isActive
                      ? 'bg-[#00FF96]/10 text-[#00FF96] border-[#00FF96]'
                      : 'text-white/70 hover:text-[#00FFAA] hover:bg-white/5'
                    }
                  `}
                >
                  [{item.label}]

                  {/* LED Indicator */}
                  {isActive && (
                    <motion.div
                      className="absolute -top-1 -right-1 w-2 h-2 bg-[#00FF96] rounded-full"
                      animate={{ opacity: [1, 0.3, 1] }}
                      transition={{ duration: 1.5, repeat: Infinity }}
                    />
                  )}
                </motion.div>
              </Link>
            )
          })}
        </nav>

        {/* Right: Status Area + CTA (Desktop) */}
        <div className="hidden lg:flex items-center space-x-6">
          {/* Status Display */}
          <div className="flex flex-col space-y-1 font-mono text-[10px] text-white/60 tracking-wider">
            <div className="flex items-center space-x-2">
              <motion.span
                className="text-[#00FF96]"
                animate={{ opacity: [1, 0.5, 1] }}
                transition={{ duration: 2, repeat: Infinity }}
              >
                ⚙
              </motion.span>
              <span>SYSTEM: <span className="text-[#00FF96]">ACTIVE</span></span>
            </div>
            <div className="flex items-center space-x-2">
              <span className="text-[#78C4D4]">🧪</span>
              <span>EXPERIMENTS: <span className="text-[#78C4D4]">{experiments}</span></span>
            </div>
            <div className="flex items-center space-x-2">
              <span className="text-[#00C896]">💬</span>
              <span>CONTACT: <span className="text-[#00C896]">OPEN</span></span>
            </div>
          </div>

          {/* CTA Button */}
          <Link href="/contact">
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              animate={{
                boxShadow: [
                  '0 0 15px rgba(239, 68, 68, 0.7)',
                  '0 0 30px rgba(239, 68, 68, 0.4)',
                  '0 0 15px rgba(239, 68, 68, 0.7)'
                ]
              }}
              transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
              className="
                font-mono text-xs px-6 py-3 bg-red-600 hover:bg-red-700
                text-white font-bold uppercase tracking-wider
                border-2 border-red-500
                relative overflow-hidden
              "
            >
              <span className="relative z-10 flex items-center gap-1">
                <span className="text-yellow-300 text-sm">⚠</span>
                新規相談
              </span>
              <motion.div
                className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
                animate={{ x: ['-100%', '200%'] }}
                transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
              />
            </motion.button>
          </Link>
        </div>

        {/* Mobile Menu Toggle */}
        <button
          onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
          className="lg:hidden p-2 text-white/70 hover:text-white transition-colors"
          aria-label="メニューを開く"
        >
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            {mobileMenuOpen ? (
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            ) : (
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            )}
          </svg>
        </button>
      </div>

      {/* Mobile Slide-in Panel */}
      {mobileMenuOpen && (
        <motion.div
          initial={{ x: '100%' }}
          animate={{ x: 0 }}
          exit={{ x: '100%' }}
          transition={{ type: 'tween', duration: 0.3 }}
          className="lg:hidden absolute top-full left-0 w-full bg-black/98 border-b border-[#333] backdrop-blur-sm"
        >
          <div className="container mx-auto px-4 py-6 space-y-4">
            {/* Mobile Navigation */}
            {navItems.map((item) => {
              const isActive = activeTab === item.label

              return (
                <Link
                  key={item.label}
                  href={item.href}
                  onClick={() => setMobileMenuOpen(false)}
                  className={`
                    block font-mono text-sm px-4 py-3 border border-[#333]
                    transition-all duration-300 uppercase tracking-wider
                    ${isActive
                      ? 'bg-[#00FF96]/10 text-[#00FF96] border-[#00FF96]'
                      : 'text-white/70 hover:text-[#00FFAA] hover:bg-white/5'
                    }
                  `}
                >
                  [{item.label}]
                </Link>
              )
            })}

            {/* Mobile CTA */}
            <Link
              href="/contact"
              onClick={() => setMobileMenuOpen(false)}
              className="block font-mono text-sm px-6 py-3 bg-red-600 hover:bg-red-700 text-white font-bold uppercase tracking-wider border-2 border-red-500 text-center transition-all duration-300 shadow-[0_0_15px_rgba(239,68,68,0.6)]"
            >
              <span className="inline-flex items-center gap-2">
                <span className="text-yellow-300">⚠</span>
                新規相談
                <span className="text-yellow-300">⚠</span>
              </span>
            </Link>

            {/* Mobile Status */}
            <div className="flex flex-col space-y-2 font-mono text-xs text-white/60 tracking-wider pt-4 border-t border-[#333]">
              <div className="flex items-center space-x-2">
                <span className="text-[#00FF96]">⚙</span>
                <span>SYSTEM: <span className="text-[#00FF96]">ACTIVE</span></span>
              </div>
              <div className="flex items-center space-x-2">
                <span className="text-[#78C4D4]">🧪</span>
                <span>EXPERIMENTS: <span className="text-[#78C4D4]">{experiments}</span></span>
              </div>
              <div className="flex items-center space-x-2">
                <span className="text-[#00C896]">💬</span>
                <span>CONTACT: <span className="text-[#00C896]">OPEN</span></span>
              </div>
            </div>
          </div>
        </motion.div>
      )}
    </header>
  )
}
