// Generated by ClaudeCode - Hero Section (Cyber Style)
'use client'

import { motion } from 'framer-motion'

export default function HeroSection() {
  return (
    <section className="min-h-screen flex items-center relative overflow-hidden bg-black text-white pt-20">
      {/* Background Grid Pattern */}
      <div className="absolute inset-0 opacity-10">
        <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <pattern id="hero-grid" width="40" height="40" patternUnits="userSpaceOnUse">
              <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#hero-grid)" />
        </svg>
      </div>

      {/* Scan Line Effect */}
      <motion.div
        className="absolute inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/5 to-transparent pointer-events-none"
        animate={{ y: ['-100%', '200%'] }}
        transition={{ duration: 8, repeat: Infinity, ease: 'linear' }}
      />

      <div className="container mx-auto px-6 md:px-12 lg:px-24 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: -30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="max-w-5xl space-y-8"
        >
          {/* Kicker */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest inline-block border-l-4 border-[#78C4D4] pl-4"
          >
            [SYSTEM_ONLINE] LAB_INITIALIZED
          </motion.div>

          {/* Main Title */}
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            className="font-mono text-4xl md:text-6xl lg:text-7xl font-bold leading-tight tracking-tight"
          >
            {'>'} 業務課題を、
            <br />
            <span className="text-[#00FF96]">実験</span>で仕組みに変える
            <br />
            研究所。
          </motion.h1>

          {/* Description */}
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.5 }}
            className="text-base md:text-lg text-white/70 leading-relaxed max-w-3xl mx-auto font-mono"
          >
            {'// '}3125 LABは、企業が抱えるニッチな業務課題を実験的に解決する開発スタジオです
            <br />
            {'// '}AI × ローコード × API統合で、高速プロトタイピングを実現
          </motion.p>

          {/* Stats */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.6 }}
            className="flex gap-8 flex-wrap font-mono text-xs"
          >
            <div className="flex items-center space-x-2">
              <motion.span
                className="text-[#00FF96]"
                animate={{ opacity: [1, 0.3, 1] }}
                transition={{ duration: 2, repeat: Infinity }}
              >
                ●
              </motion.span>
              <span className="text-white/60">PROJECTS: <span className="text-[#00FF96]">50+</span></span>
            </div>
            <div className="flex items-center space-x-2">
              <span className="text-[#78C4D4]">●</span>
              <span className="text-white/60">CLIENTS: <span className="text-[#78C4D4]">30+</span></span>
            </div>
            <div className="flex items-center space-x-2">
              <span className="text-[#00C896]">●</span>
              <span className="text-white/60">SUCCESS_RATE: <span className="text-[#00C896]">98%</span></span>
            </div>
          </motion.div>

          {/* CTA Button */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.7 }}
          >
            <a href="/contact">
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                animate={{
                  boxShadow: [
                    '0 0 20px rgba(239, 68, 68, 0.8)',
                    '0 0 40px rgba(239, 68, 68, 0.4)',
                    '0 0 20px rgba(239, 68, 68, 0.8)'
                  ]
                }}
                transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                className="font-mono text-sm px-10 py-5 bg-red-600 hover:bg-red-700 text-white font-bold uppercase tracking-wider border-2 border-red-500 relative overflow-hidden"
              >
                <span className="relative z-10 flex items-center gap-2">
                  <span className="text-yellow-300">⚠</span>
                  {'>'} 無料相談を開始
                  <span className="text-yellow-300">⚠</span>
                </span>
                <motion.div
                  className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
                  animate={{ x: ['-100%', '200%'] }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
                />
              </motion.button>
            </a>
          </motion.div>

          {/* Additional Info */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.9 }}
            className="flex gap-6 text-xs font-mono text-white/40 pt-4 flex-wrap"
          >
            <div>RESPONSE: 2営業日以内</div>
            <div>|</div>
            <div>NDA: 対応可能</div>
            <div>|</div>
            <div>CONSULTATION: 無料</div>
          </motion.div>
        </motion.div>

        {/* Scroll indicator */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.5 }}
          className="absolute bottom-8 left-1/2 transform -translate-x-1/2"
        >
          <motion.div
            animate={{ y: [0, 10, 0] }}
            transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
            className="text-white/40 text-xs font-mono uppercase tracking-widest"
          >
            {'['} SCROLL_DOWN {']'}
            <div className="text-center mt-1">▼</div>
          </motion.div>
        </motion.div>
      </div>

      {/* Corner Decorations */}
      <div className="absolute top-8 left-8 w-16 h-16 border-t-2 border-l-2 border-[#78C4D4] opacity-50" />
      <div className="absolute top-8 right-8 w-16 h-16 border-t-2 border-r-2 border-[#78C4D4] opacity-50" />
      <div className="absolute bottom-8 left-8 w-16 h-16 border-b-2 border-l-2 border-[#78C4D4] opacity-50" />
      <div className="absolute bottom-8 right-8 w-16 h-16 border-b-2 border-r-2 border-[#78C4D4] opacity-50" />
    </section>
  )
}
