// Generated by ClaudeCode
'use client'

import { motion } from 'framer-motion'
import OfficeWorker from '@/components/illustrations/OfficeWorker'

const problems = [
  { text: '手入力が多く、人的ミスが発生している', color: 'red' },
  { text: 'Excel管理が限界を迎えている', color: 'yellow' },
  { text: 'データを毎回集計・コピーしている', color: 'red' },
  { text: '属人化していて、引き継ぎが難しい', color: 'yellow' },
]

export default function ProblemSection() {
  return (
    <section className="section-padding relative bg-black overflow-hidden" id="problem">
      {/* Red Alert Background Animation */}
      <motion.div
        className="absolute inset-0 bg-gradient-to-br from-red-950/80 via-black to-red-950/80"
        animate={{
          opacity: [0.3, 0.5, 0.3],
        }}
        transition={{
          duration: 3,
          repeat: Infinity,
          ease: 'easeInOut',
        }}
      />

      {/* Grid Pattern */}
      <div className="absolute inset-0 opacity-20">
        <div className="grid-pattern w-full h-full" style={{
          backgroundImage: 'linear-gradient(red 1px, transparent 1px), linear-gradient(90deg, red 1px, transparent 1px)',
          backgroundSize: '20px 20px'
        }} />
      </div>

      {/* Pulsing Red Corner Alerts */}
      <motion.div
        className="absolute top-8 right-8 w-4 h-4 bg-red-600 rounded-full"
        animate={{
          scale: [1, 1.5, 1],
          opacity: [1, 0.5, 1],
        }}
        transition={{
          duration: 1.5,
          repeat: Infinity,
        }}
      />
      <motion.div
        className="absolute bottom-8 left-8 w-4 h-4 bg-red-600 rounded-full"
        animate={{
          scale: [1, 1.5, 1],
          opacity: [1, 0.5, 1],
        }}
        transition={{
          duration: 1.5,
          repeat: Infinity,
          delay: 0.75,
        }}
      />

      <div className="container-custom relative z-10">
        {/* Alert Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-4"
        >
          <motion.div
            className="inline-block bg-red-600 border-4 border-red-400 px-8 py-3 font-mono font-bold text-white text-xl mb-6"
            animate={{
              boxShadow: [
                '0 0 20px rgba(220, 38, 38, 0.8)',
                '0 0 40px rgba(220, 38, 38, 0.8)',
                '0 0 20px rgba(220, 38, 38, 0.8)',
              ],
            }}
            transition={{
              duration: 2,
              repeat: Infinity,
            }}
          >
            ⚠ WARNING ⚠
          </motion.div>
        </motion.div>

        {/* Section Label */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-sm font-mono text-red-400 border-l-4 border-red-600 pl-4 mb-8 bg-black/50 py-2"
        >
          #02 PROBLEM IDENTIFICATION - CRITICAL ALERT
        </motion.div>

        {/* Title */}
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-4xl md:text-5xl font-bold mb-12 text-center text-white"
        >
          <span className="text-red-500">【観察結果】</span>
          <br />
          多くの企業が抱える
          <br />
          <span className="text-red-400">課題</span>
        </motion.h2>

        <div className="grid lg:grid-cols-2 gap-16 items-center">
          {/* Problems List */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="space-y-6"
          >
            {problems.map((problem, index) => {
              const isRed = problem.color === 'red'
              const bgColor = isRed ? 'bg-red-950/90' : 'bg-yellow-900/80'
              const borderColor = isRed ? 'border-red-500' : 'border-yellow-400'
              const badgeBg = isRed ? 'bg-red-600' : 'bg-yellow-500'
              const textColor = isRed ? 'text-red-100' : 'text-yellow-100'

              return (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: 0.3 + index * 0.1 }}
                  className={`flex items-start space-x-4 ${bgColor} p-6 rounded-lg border-4 ${borderColor} hover:-translate-y-1 transition-all duration-300 relative overflow-hidden backdrop-blur-sm`}
                  animate={{
                    boxShadow: [
                      `0 0 30px ${isRed ? 'rgba(239, 68, 68, 0.4)' : 'rgba(234, 179, 8, 0.4)'}`,
                      `0 0 50px ${isRed ? 'rgba(239, 68, 68, 0.6)' : 'rgba(234, 179, 8, 0.6)'}`,
                      `0 0 30px ${isRed ? 'rgba(239, 68, 68, 0.4)' : 'rgba(234, 179, 8, 0.4)'}`,
                    ],
                  }}
                  transition={{
                    duration: 2,
                    repeat: Infinity,
                    delay: index * 0.5,
                  }}
                >
                  {/* Animated Warning stripe pattern */}
                  <motion.div
                    className={`absolute left-0 top-0 bottom-0 w-4`}
                    style={{
                      backgroundImage: isRed
                        ? 'repeating-linear-gradient(45deg, #dc2626, #dc2626 10px, #000000 10px, #000000 20px)'
                        : 'repeating-linear-gradient(45deg, #eab308, #eab308 10px, #000000 10px, #000000 20px)'
                    }}
                    animate={{
                      opacity: [1, 0.7, 1],
                    }}
                    transition={{
                      duration: 1,
                      repeat: Infinity,
                    }}
                  />

                  {/* DANGER label */}
                  <div className="absolute top-2 right-2 bg-red-600 text-white text-xs font-mono font-bold px-2 py-1 border border-red-400 opacity-90">
                    DANGER
                  </div>

                  {/* Warning icon badge with pulse */}
                  <motion.div
                    className={`flex-shrink-0 w-12 h-12 ${badgeBg} flex items-center justify-center text-white font-bold border-4 border-black z-10`}
                    animate={{
                      scale: [1, 1.1, 1],
                    }}
                    transition={{
                      duration: 1.5,
                      repeat: Infinity,
                      delay: index * 0.3,
                    }}
                  >
                    <svg viewBox="0 0 24 24" className="w-7 h-7" fill="none" stroke="currentColor" strokeWidth="3">
                      <path d="M12 9v4m0 4h.01M12 3L2 21h20L12 3z" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  </motion.div>

                  <div className="flex-1 z-10">
                    <p className={`text-lg leading-relaxed pt-1.5 font-bold ${textColor}`}>
                      {problem.text}
                    </p>
                    <div className="mt-2 flex items-center space-x-2">
                      <span className="text-xs font-mono text-red-400 bg-black/50 px-2 py-1 border border-red-600">
                        STATUS: CRITICAL
                      </span>
                    </div>
                  </div>
                </motion.div>
              )
            })}
          </motion.div>

          {/* Illustration */}
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8, delay: 0.5 }}
            className="relative"
          >
            {/* Red Alert Frame */}
            <motion.div
              className="absolute inset-0 border-8 border-red-600 rounded-2xl"
              animate={{
                opacity: [0.5, 1, 0.5],
                borderColor: ['#dc2626', '#ef4444', '#dc2626'],
              }}
              transition={{
                duration: 2,
                repeat: Infinity,
              }}
            />

            {/* Main illustration container */}
            <div className="bg-red-950/70 p-8 rounded-2xl border-4 border-red-500 shadow-[8px_8px_0px_0px_rgba(220,38,38,0.8)] backdrop-blur-sm relative z-10">
              <div className="bg-white/90 p-4 rounded-xl">
                <OfficeWorker />
              </div>

              {/* System Failure Text */}
              <motion.div
                className="mt-4 bg-black border-2 border-red-600 p-3"
                animate={{
                  backgroundColor: ['#000000', '#1a0000', '#000000'],
                }}
                transition={{
                  duration: 1.5,
                  repeat: Infinity,
                }}
              >
                <div className="text-red-500 font-mono text-sm font-bold text-center">
                  ⚠ SYSTEM OVERLOAD ⚠
                </div>
                <div className="text-red-300 font-mono text-xs text-center mt-1">
                  業務崩壊の危機
                </div>
              </motion.div>
            </div>

            {/* Floating Alert Markers */}
            <motion.div
              className="absolute -top-6 -right-6 w-16 h-16 bg-red-600 border-4 border-red-400 flex items-center justify-center font-mono font-bold text-white text-xs"
              animate={{
                rotate: [0, 5, -5, 0],
                scale: [1, 1.2, 1],
                boxShadow: [
                  '0 0 20px rgba(220, 38, 38, 0.8)',
                  '0 0 40px rgba(220, 38, 38, 1)',
                  '0 0 20px rgba(220, 38, 38, 0.8)',
                ],
              }}
              transition={{
                duration: 1.5,
                repeat: Infinity,
                ease: 'easeInOut',
              }}
            >
              <div className="text-center">
                <div className="text-2xl">⚠</div>
                <div className="text-[8px]">ALERT</div>
              </div>
            </motion.div>

            <motion.div
              className="absolute -bottom-6 -left-6 w-16 h-16 bg-yellow-500 border-4 border-yellow-300 flex items-center justify-center font-mono font-bold text-black text-xs"
              animate={{
                rotate: [0, -5, 5, 0],
                scale: [1, 1.2, 1],
                boxShadow: [
                  '0 0 20px rgba(234, 179, 8, 0.8)',
                  '0 0 40px rgba(234, 179, 8, 1)',
                  '0 0 20px rgba(234, 179, 8, 0.8)',
                ],
              }}
              transition={{
                duration: 1.5,
                repeat: Infinity,
                ease: 'easeInOut',
                delay: 0.75,
              }}
            >
              <div className="text-center">
                <div className="text-2xl">⚠</div>
                <div className="text-[8px]">CAUTION</div>
              </div>
            </motion.div>

            {/* Danger Stripes */}
            <div className="absolute top-0 right-0 w-20 h-20 overflow-hidden opacity-80">
              <div className="absolute inset-0" style={{
                backgroundImage: 'repeating-linear-gradient(45deg, #dc2626, #dc2626 10px, #000000 10px, #000000 20px)'
              }} />
            </div>
            <div className="absolute bottom-0 left-0 w-20 h-20 overflow-hidden opacity-80">
              <div className="absolute inset-0" style={{
                backgroundImage: 'repeating-linear-gradient(-45deg, #eab308, #eab308 10px, #000000 10px, #000000 20px)'
              }} />
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
