// Generated by ClaudeCode
'use client'

import { motion } from 'framer-motion'

const services = [
  {
    name: 'Lite',
    icon: '[LTE]',
    price: '¥50,000〜',
    description: '小規模な業務改善実験',
    features: [
      'ヒアリング & 要件定義',
      'プロトタイプ構築',
      '1週間〜2週間納品',
      '1ヶ月サポート',
    ],
  },
  {
    name: 'Business',
    icon: '[BIZ]',
    price: '¥200,000〜',
    description: '本格的な業務システム開発',
    features: [
      '詳細設計 & 開発',
      'データベース構築',
      '2週間〜1ヶ月納品',
      '3ヶ月保守サポート',
    ],
    highlighted: true,
  },
  {
    name: 'Custom',
    icon: '[CTM]',
    price: '応相談',
    description: '完全カスタムソリューション',
    features: [
      '要件に応じた設計',
      'フルスクラッチ開発',
      'API連携・外部サービス統合',
      '継続的な改善サポート',
    ],
  },
]

export default function ServiceSection() {
  return (
    <section className="section-padding relative overflow-hidden" id="service">
      {/* Circuit board pattern background */}
      <div className="absolute inset-0 opacity-5">
        <svg className="w-full h-full" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <pattern id="circuit" x="0" y="0" width="100" height="100" patternUnits="userSpaceOnUse">
              <circle cx="10" cy="10" r="2" fill="#000000" />
              <circle cx="90" cy="90" r="2" fill="#000000" />
              <line x1="10" y1="10" x2="50" y2="10" stroke="#000000" strokeWidth="1" />
              <line x1="50" y1="10" x2="50" y2="50" stroke="#000000" strokeWidth="1" />
              <line x1="50" y1="50" x2="90" y2="50" stroke="#000000" strokeWidth="1" />
              <line x1="90" y1="50" x2="90" y2="90" stroke="#000000" strokeWidth="1" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#circuit)" />
        </svg>
      </div>

      <div className="container-custom relative z-10">
        {/* Section Label */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-sm font-mono text-accent border-l-4 border-accent pl-4 mb-8"
        >
          #04 SERVICE PLANS
        </motion.div>

        {/* Title */}
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-4xl md:text-5xl font-bold mb-16 text-center"
        >
          提供<span className="text-accent">プラン</span>
        </motion.h2>

        {/* Service Cards */}
        <div className="grid md:grid-cols-3 gap-8 max-w-7xl mx-auto">
          {services.map((service, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 + index * 0.1 }}
              whileHover={{
                y: -10,
                transition: { duration: 0.3 },
              }}
              className={`bg-white border-2 border-black rounded-xl p-8 shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] transition-all duration-300 ${
                service.highlighted
                  ? 'ring-4 ring-accent ring-offset-4 relative'
                  : ''
              }`}
            >
              {service.highlighted && (
                <div className="absolute -top-4 left-1/2 transform -translate-x-1/2 bg-accent text-white px-4 py-1 rounded-full text-sm font-bold border-2 border-black">
                  人気
                </div>
              )}

              {/* Icon */}
              <div className="font-mono text-5xl font-bold mb-4 text-accent">{service.icon}</div>

              {/* Plan Name */}
              <h3 className="text-3xl font-bold mb-2">{service.name}</h3>

              {/* Price */}
              <p className="text-2xl font-mono text-accent mb-4 font-bold">
                {service.price}
              </p>

              {/* Description */}
              <p className="text-foreground/80 mb-6 min-h-[3rem]">
                {service.description}
              </p>

              {/* Divider */}
              <div className="border-t-2 border-black/10 my-6" />

              {/* Features */}
              <ul className="space-y-3">
                {service.features.map((feature, featureIndex) => (
                  <li
                    key={featureIndex}
                    className="flex items-start space-x-3"
                  >
                    <span className="text-accent mt-1">✓</span>
                    <span className="text-sm leading-relaxed">{feature}</span>
                  </li>
                ))}
              </ul>

              {/* CTA Button */}
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                animate={{
                  boxShadow: [
                    '0 0 15px rgba(239, 68, 68, 0.7)',
                    '0 0 30px rgba(239, 68, 68, 0.4)',
                    '0 0 15px rgba(239, 68, 68, 0.7)'
                  ]
                }}
                transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                className="w-full mt-8 bg-red-600 hover:bg-red-700 text-white font-bold py-3 px-6 rounded-lg border-2 border-red-500 relative overflow-hidden"
              >
                <span className="relative z-10 flex items-center justify-center gap-2">
                  <span className="text-yellow-300">⚠</span>
                  詳細を見る
                  <span className="text-yellow-300">⚠</span>
                </span>
                <motion.div
                  className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
                  animate={{ x: ['-100%', '200%'] }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
                />
              </motion.button>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
