// Generated by ClaudeCode (Cyber Style - Simplified)
'use client'

import { motion } from 'framer-motion'

export default function SolutionSection() {
  return (
    <section className="relative bg-black text-white py-24 px-6 md:px-12 lg:px-24" id="solution">
      {/* Background Grid Pattern */}
      <div className="absolute inset-0 opacity-10 pointer-events-none">
        <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <pattern id="solution-grid" width="40" height="40" patternUnits="userSpaceOnUse">
              <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#solution-grid)" />
        </svg>
      </div>

      <div className="container mx-auto max-w-6xl relative z-10">
        {/* Section Label */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest border-l-4 border-[#78C4D4] pl-4 mb-8 inline-block"
        >
          [SECTION_03] SOLUTION_APPROACH
        </motion.div>

        {/* Main Content */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="space-y-12"
        >
          {/* Title and Description */}
          <div className="space-y-6 max-w-4xl">
            <h2 className="font-mono text-3xl md:text-4xl lg:text-5xl font-bold leading-tight">
              {'>'} 課題 × 実験 × <span className="text-[#00FF96]">システム化</span>
            </h2>

            <p className="font-mono text-base md:text-lg text-white/70 leading-relaxed">
              {'// '}業務課題を<span className="text-[#00FF96]">"研究テーマ"</span>として扱い、小規模・短納期で<span className="text-[#78C4D4]">"実験的システム"</span>を構築。
              <br />
              {'// '}必要ならそのまま正式導入までサポートします。
            </p>
          </div>

          {/* Feature Grid */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { icon: '[EXP]', label: '実験的\nアプローチ', color: '#00FF96' },
              { icon: '[RPD]', label: '短納期・\n小規模', color: '#78C4D4' },
              { icon: '[AI]', label: 'AI ×\nローコード', color: '#00FF96' },
              { icon: '[PHS]', label: '段階的\n導入', color: '#78C4D4' },
            ].map((item, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: 0.2 + index * 0.1 }}
                className="bg-black border border-[#333] hover:border-[#78C4D4] p-6 text-center relative overflow-hidden group transition-all duration-300"
              >
                <motion.div
                  className="absolute inset-0 bg-gradient-to-b from-[#78C4D4]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"
                />
                <div className="relative z-10 space-y-3">
                  <div className="font-mono text-2xl font-bold" style={{ color: item.color }}>{item.icon}</div>
                  <div className="font-mono text-sm text-white/80 whitespace-pre-line">{item.label}</div>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  )
}
