// Generated by ClaudeCode
'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import Whiteboard from '@/components/illustrations/Whiteboard'

const works = [
  {
    caseNumber: '01',
    title: 'LP制作',
    client: 'スタートアップ企業',
    description: '企業のランディングページを研究所風デザインで制作。モダンなアニメーションで独自性の高いブランディングを実現。',
    tags: ['Next.js', 'Tailwind CSS', 'Framer Motion'],
  },
  {
    caseNumber: '02',
    title: 'HP制作',
    client: '中小企業',
    description: 'コーポレートサイトをフルリニューアル。レスポンシブ対応、SEO最適化を実装。',
    tags: ['WordPress', 'PHP', 'Google Analytics'],
  },
  {
    caseNumber: '03',
    title: '請求書管理システム',
    client: '営業代行企業',
    description: 'Excel管理からクラウドベースの自動請求システムへ移行。月40時間の工数削減を実現。',
    tags: ['AI-OCR', 'Zapier', 'Google Apps Script'],
  },
  {
    caseNumber: '04',
    title: '契約書管理システム',
    client: '人材系会社',
    description: '契約書の電子化と一元管理システムを構築。検索機能、期限アラート、承認フローを実装。',
    tags: ['Airtable', 'Slack API', 'Box API'],
  },
  {
    caseNumber: '05',
    title: '人事評価システム',
    client: 'セールス企業',
    description: '営業成績に基づく評価システムとランク自動判定機能を実装。評価プロセスの透明化と公平性を向上。',
    tags: ['Airtable', 'Make.com', 'Slack連携'],
  },
  {
    caseNumber: '06',
    title: 'プロジェクト管理システム',
    client: 'Web制作会社',
    description: '複数プロジェクトの進捗管理、タスク割り当て、工数管理を一元化。ガントチャート表示を実装。',
    tags: ['Notion API', 'Python', 'Google Data Studio'],
  },
]

export default function WorksSection() {
  return (
    <section className="section-padding relative bg-white" id="works">
      <div className="container-custom">
        {/* Section Label */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-sm font-mono text-accent border-l-4 border-accent pl-4 mb-8"
        >
          #05 RESEARCH RESULTS
        </motion.div>

        {/* Title */}
        <motion.h2
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-4xl md:text-5xl font-bold mb-12 text-center"
        >
          これまでの<span className="text-accent">研究成果</span>
        </motion.h2>

        {/* Illustration */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="max-w-2xl mx-auto mb-16"
        >
          <Whiteboard />
        </motion.div>

        {/* Works Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-7xl mx-auto">
          {works.map((work, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.3 + index * 0.1 }}
              className="bg-background border-2 border-black rounded-xl p-6 shadow-[5px_5px_0px_0px_rgba(0,0,0,1)] hover:shadow-[7px_7px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-2 transition-all duration-300 relative overflow-hidden"
            >
              {/* Case Label - Notebook style */}
              <div className="absolute -top-3 -left-3 bg-accent text-white font-mono font-bold px-4 py-2 rounded-br-xl border-2 border-black shadow-[3px_3px_0px_0px_rgba(0,0,0,1)]">
                Case {work.caseNumber}
              </div>

              {/* Content */}
              <div className="mt-6">
                <h3 className="text-2xl font-bold mb-2">{work.title}</h3>

                <p className="text-sm text-accent font-mono mb-4">
                  for {work.client}
                </p>

                <p className="text-foreground/80 leading-relaxed mb-6">
                  {work.description}
                </p>

                {/* Tags */}
                <div className="flex flex-wrap gap-2">
                  {work.tags.map((tag, tagIndex) => (
                    <span
                      key={tagIndex}
                      className="bg-white border border-black px-3 py-1 rounded-full text-xs font-mono"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              </div>

              {/* Decorative corner */}
              <div className="absolute bottom-0 right-0 w-16 h-16 opacity-10">
                <svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                  <circle cx="80" cy="80" r="40" fill="#78C4D4" />
                  <circle cx="90" cy="70" r="30" fill="#000000" />
                </svg>
              </div>
            </motion.div>
          ))}
        </div>

        {/* See More Button */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.8 }}
          className="text-center mt-12"
        >
          <Link href="/works" className="inline-block bg-white hover:bg-background text-foreground font-bold px-8 py-4 rounded-lg border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:-translate-y-1 transition-all duration-300">
            もっと見る →
          </Link>
        </motion.div>
      </div>
    </section>
  )
}
