// Generated by ClaudeCode - 共通アイコンコンポーネント
'use client'

interface IconProps {
  className?: string
  size?: number
}

// ビーカー（ロゴ用）
export function BeakerIcon({ className = "w-6 h-6", size = 24 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path
        d="M9 3V7L5 17C4.5 18 4.5 19 5.5 19.5C6 19.8 6.5 20 7 20H17C17.5 20 18 19.8 18.5 19.5C19.5 19 19.5 18 19 17L15 7V3"
        stroke="currentColor"
        strokeWidth="2"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <rect x="8" y="1" width="8" height="2" rx="1" fill="currentColor" />
      <path d="M8 13 Q 12 11 16 13" stroke="currentColor" strokeWidth="1.5" fill="none" />
      <circle cx="10" cy="15" r="1" fill="currentColor" opacity="0.6" />
      <circle cx="14" cy="16" r="1" fill="currentColor" opacity="0.6" />
    </svg>
  )
}

// メール
export function MailIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <rect x="3" y="5" width="18" height="14" rx="2" stroke="currentColor" strokeWidth="2" fill="none" />
      <path d="M3 7 L12 13 L21 7" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// 場所/ピン
export function LocationIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path
        d="M12 2C8.13 2 5 5.13 5 9C5 13.17 9.42 18.92 11.24 21.11C11.64 21.59 12.36 21.59 12.76 21.11C14.58 18.92 19 13.17 19 9C19 5.13 15.87 2 12 2Z"
        stroke="currentColor"
        strokeWidth="2"
        fill="none"
      />
      <circle cx="12" cy="9" r="2.5" fill="currentColor" />
    </svg>
  )
}

// 時計
export function ClockIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <circle cx="12" cy="12" r="9" stroke="currentColor" strokeWidth="2" fill="none" />
      <path d="M12 6 V12 L16 14" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// タイマー
export function TimerIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <circle cx="12" cy="13" r="8" stroke="currentColor" strokeWidth="2" fill="none" />
      <path d="M12 9 V13 L15 15" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
      <rect x="9" y="2" width="6" height="3" rx="1" stroke="currentColor" strokeWidth="1.5" fill="none" />
      <path d="M17 6 L19 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  )
}

// 電球/アイデア
export function IdeaIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path
        d="M12 2C8.5 2 6 4.5 6 8C6 10.5 7 12 8 14C8.5 14.5 9 15.5 9 16V17C9 17.5 9.5 18 10 18H14C14.5 18 15 17.5 15 17V16C15 15.5 15.5 14.5 16 14C17 12 18 10.5 18 8C18 4.5 15.5 2 12 2Z"
        stroke="currentColor"
        strokeWidth="2"
        fill="none"
      />
      <path d="M9 18 V19 C9 20.1 9.9 21 11 21 H13 C14.1 21 15 20.1 15 19 V18" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" />
      <line x1="12" y1="8" x2="12" y2="12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  )
}

// 鍵/セキュリティ
export function LockIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <rect x="5" y="11" width="14" height="10" rx="2" stroke="currentColor" strokeWidth="2" fill="none" />
      <path d="M8 11 V7 C8 4.8 9.8 3 12 3 C14.2 3 16 4.8 16 7 V11" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" />
      <circle cx="12" cy="16" r="1.5" fill="currentColor" />
    </svg>
  )
}

// メモ/書類
export function DocumentIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path
        d="M7 3 H13 L17 7 V19 C17 20.1 16.1 21 15 21 H7 C5.9 21 5 20.1 5 19 V5 C5 3.9 5.9 3 7 3Z"
        stroke="currentColor"
        strokeWidth="2"
        fill="none"
      />
      <path d="M13 3 V7 H17" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
      <line x1="8" y1="12" x2="14" y2="12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="8" y1="15" x2="14" y2="15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
    </svg>
  )
}

// 吹き出し/チャット
export function ChatIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path
        d="M3 6 C3 4.3 4.3 3 6 3 H18 C19.7 3 21 4.3 21 6 V14 C21 15.7 19.7 17 18 17 H10 L6 21 V17 H6 C4.3 17 3 15.7 3 14 Z"
        stroke="currentColor"
        strokeWidth="2"
        fill="none"
        strokeLinejoin="round"
      />
      <line x1="8" y1="8" x2="16" y2="8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
      <line x1="8" y1="12" x2="13" y2="12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
    </svg>
  )
}

// 人々/ユーザー
export function UsersIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <circle cx="9" cy="7" r="3" stroke="currentColor" strokeWidth="2" fill="none" />
      <path d="M3 19 C3 15.7 5.7 13 9 13 C12.3 13 15 15.7 15 19" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" />
      <circle cx="17" cy="7" r="2.5" stroke="currentColor" strokeWidth="2" fill="none" />
      <path d="M19 13 C20.7 13.5 22 15.1 22 17" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" />
    </svg>
  )
}

// グラフ/成長
export function ChartIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path d="M3 20 L7 16 L11 18 L21 8" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M21 8 L21 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      <path d="M21 8 L17 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      <circle cx="7" cy="16" r="1.5" fill="currentColor" />
      <circle cx="11" cy="18" r="1.5" fill="currentColor" />
      <circle cx="21" cy="8" r="1.5" fill="currentColor" />
    </svg>
  )
}

// 警告/注意
export function AlertIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path
        d="M12 2 L22 20 H2 Z"
        stroke="currentColor"
        strokeWidth="2"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <line x1="12" y1="10" x2="12" y2="14" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
      <circle cx="12" cy="17" r="1" fill="currentColor" />
    </svg>
  )
}

// チェック/成功
export function CheckIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path d="M5 13 L9 17 L19 7" stroke="currentColor" strokeWidth="2.5" fill="none" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// 矢印（右）
export function ArrowRightIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path d="M5 12 H19 M19 12 L13 6 M19 12 L13 18" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  )
}

// ホーム
export function HomeIcon({ className = "w-5 h-5", size = 20 }: IconProps) {
  return (
    <svg viewBox="0 0 24 24" className={className} width={size} height={size} xmlns="http://www.w3.org/2000/svg">
      <path d="M3 12 L12 3 L21 12 V20 C21 20.5 20.5 21 20 21 H4 C3.5 21 3 20.5 3 20 Z" stroke="currentColor" strokeWidth="2" fill="none" strokeLinejoin="round" />
      <path d="M9 21 V12 H15 V21" stroke="currentColor" strokeWidth="2" fill="none" />
    </svg>
  )
}
