// Generated by ClaudeCode - フローステップ用のSVGアイコン
'use client'

interface IconProps {
  className?: string
}

// ヒアリング（マイク/会話）
export function ListenIcon({ className = "w-16 h-16" }: IconProps) {
  return (
    <svg viewBox="0 0 100 100" className={className} xmlns="http://www.w3.org/2000/svg">
      {/* Outer circle */}
      <circle cx="50" cy="50" r="45" fill="#78C4D4" opacity="0.2" />

      {/* Sound waves */}
      <path
        d="M 70 40 Q 75 50 70 60"
        stroke="#78C4D4"
        strokeWidth="3"
        fill="none"
        strokeLinecap="round"
      />
      <path
        d="M 77 35 Q 85 50 77 65"
        stroke="#78C4D4"
        strokeWidth="3"
        fill="none"
        strokeLinecap="round"
      />

      {/* Microphone/ear */}
      <ellipse cx="45" cy="50" rx="15" ry="20" fill="#000000" />
      <ellipse cx="45" cy="50" rx="10" ry="15" fill="#FFFFFF" />
      <circle cx="45" cy="50" r="5" fill="#78C4D4" />

      {/* Stand */}
      <rect x="43" y="65" width="4" height="10" fill="#000000" />
      <rect x="38" y="73" width="14" height="3" fill="#000000" />
    </svg>
  )
}

// 設計・試作（定規/設計図）
export function DesignIcon({ className = "w-16 h-16" }: IconProps) {
  return (
    <svg viewBox="0 0 100 100" className={className} xmlns="http://www.w3.org/2000/svg">
      {/* Outer circle */}
      <circle cx="50" cy="50" r="45" fill="#78C4D4" opacity="0.2" />

      {/* Blueprint paper */}
      <rect x="25" y="30" width="50" height="40" fill="#FFFFFF" stroke="#000000" strokeWidth="2" rx="2" />

      {/* Grid lines */}
      <line x1="30" y1="40" x2="70" y2="40" stroke="#78C4D4" strokeWidth="1" opacity="0.5" />
      <line x1="30" y1="50" x2="70" y2="50" stroke="#78C4D4" strokeWidth="1" opacity="0.5" />
      <line x1="30" y1="60" x2="70" y2="60" stroke="#78C4D4" strokeWidth="1" opacity="0.5" />
      <line x1="40" y1="35" x2="40" y2="65" stroke="#78C4D4" strokeWidth="1" opacity="0.5" />
      <line x1="50" y1="35" x2="50" y2="65" stroke="#78C4D4" strokeWidth="1" opacity="0.5" />
      <line x1="60" y1="35" x2="60" y2="65" stroke="#78C4D4" strokeWidth="1" opacity="0.5" />

      {/* Design elements */}
      <rect x="35" y="42" width="12" height="12" fill="none" stroke="#000000" strokeWidth="2" />
      <circle cx="60" cy="48" r="6" fill="none" stroke="#000000" strokeWidth="2" />
      <path d="M 35 60 L 45 60 L 40 55 Z" fill="#000000" />

      {/* Pencil */}
      <rect x="60" y="55" width="3" height="15" fill="#FFD4A3" transform="rotate(-45 61.5 62.5)" />
      <polygon points="65,58 68,61 66,63 63,60" fill="#000000" />
    </svg>
  )
}

// 納品・導入（ロケット/配送）
export function DeployIcon({ className = "w-16 h-16" }: IconProps) {
  return (
    <svg viewBox="0 0 100 100" className={className} xmlns="http://www.w3.org/2000/svg">
      {/* Outer circle */}
      <circle cx="50" cy="50" r="45" fill="#78C4D4" opacity="0.2" />

      {/* Rocket body */}
      <ellipse cx="50" cy="55" rx="12" ry="20" fill="#000000" />
      <ellipse cx="50" cy="55" rx="8" ry="16" fill="#FFFFFF" />

      {/* Rocket window */}
      <circle cx="50" cy="50" r="5" fill="#78C4D4" />
      <circle cx="50" cy="50" r="3" fill="#FFFFFF" opacity="0.5" />

      {/* Rocket nose */}
      <path d="M 50 30 L 38 45 L 62 45 Z" fill="#000000" />
      <path d="M 50 32 L 40 45 L 60 45 Z" fill="#78C4D4" />

      {/* Fins */}
      <path d="M 38 65 L 30 75 L 38 75 Z" fill="#000000" />
      <path d="M 62 65 L 70 75 L 62 75 Z" fill="#000000" />

      {/* Flames */}
      <path d="M 45 72 Q 47 78 45 82 Q 47 80 50 82 Q 53 80 55 82 Q 53 78 55 72" fill="#FFD4A3" />
      <path d="M 47 74 Q 48 78 47 80 Q 48 79 50 80 Q 52 79 53 80 Q 52 78 53 74" fill="#FFFFFF" opacity="0.7" />

      {/* Stars */}
      <circle cx="25" cy="35" r="2" fill="#78C4D4" />
      <circle cx="75" cy="40" r="2" fill="#78C4D4" />
      <circle cx="70" cy="25" r="1.5" fill="#78C4D4" />
    </svg>
  )
}

// Pre-calculated gear teeth coordinates to avoid hydration mismatch
const GEAR_TEETH = [
  { x1: 68, y1: 50, x2: 74, y2: 50 },      // 0°
  { x1: 59, y1: 65.59, x2: 62, y2: 70.78 }, // 60°
  { x1: 41, y1: 65.59, x2: 38, y2: 70.78 }, // 120°
  { x1: 32, y1: 50, x2: 26, y2: 50 },      // 180°
  { x1: 41, y1: 34.41, x2: 38, y2: 29.22 }, // 240°
  { x1: 59, y1: 34.41, x2: 62, y2: 29.22 }, // 300°
]

// 保守・改善（ツール/メンテナンス）
export function MaintenanceIcon({ className = "w-16 h-16" }: IconProps) {
  return (
    <svg viewBox="0 0 100 100" className={className} xmlns="http://www.w3.org/2000/svg">
      {/* Outer circle */}
      <circle cx="50" cy="50" r="45" fill="#78C4D4" opacity="0.2" />

      {/* Gear */}
      <circle cx="50" cy="50" r="18" fill="#000000" />
      <circle cx="50" cy="50" r="14" fill="#FFFFFF" />
      <circle cx="50" cy="50" r="6" fill="#78C4D4" />

      {/* Gear teeth */}
      {GEAR_TEETH.map((tooth, i) => (
        <line
          key={i}
          x1={tooth.x1}
          y1={tooth.y1}
          x2={tooth.x2}
          y2={tooth.y2}
          stroke="#000000"
          strokeWidth="4"
          strokeLinecap="round"
        />
      ))}

      {/* Wrench */}
      <g transform="translate(65, 30) rotate(45)">
        <rect x="0" y="0" width="3" height="12" fill="#000000" />
        <circle cx="1.5" cy="0" r="3" fill="#000000" />
        <rect x="-1" y="-1" width="5" height="3" fill="#000000" />
      </g>

      {/* Arrows indicating improvement */}
      <path
        d="M 30 35 L 25 35 L 28 30 L 31 35 L 26 35"
        fill="#78C4D4"
      />
      <path
        d="M 70 65 L 75 65 L 72 70 L 69 65 L 74 65"
        fill="#78C4D4"
      />
    </svg>
  )
}
