// Generated by ClaudeCode - 3125 LAB Design System
import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Legacy colors (keeping for compatibility)
        background: '#EDEDED',
        foreground: '#000000',
        accent: '#78C4D4',
        // Lab Design System
        lab: {
          bg: '#FFFFFF',
          ink: '#000000',
          line: '#E5E5E5',
          blue: '#78C4D4',
          neon: '#00C896',
          neonSoft: '#00FFAA',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'var(--font-noto-sans-jp)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'var(--font-ibm-plex-mono)', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        panel: '0 0 0 1px #333',
        glow: '0 0 12px rgba(120, 196, 212, 0.45)',
      },
      keyframes: {
        blink: {
          '0%, 49%': { opacity: '1' },
          '50%, 100%': { opacity: '0.3' },
        },
        breathe: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        scanline: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
      },
      animation: {
        blink: 'blink 1.2s steps(2, end) infinite',
        breathe: 'breathe 3.2s ease-in-out infinite',
        scanline: 'scanline 12s linear infinite',
      },
    },
  },
  plugins: [],
}
export default config
