// Generated by ClaudeCode - お問い合わせページ (Cyber Style)
'use client'

import { motion } from 'framer-motion'
import LoadingScreen from '@/components/LoadingScreen'
import ContactForm from '@/components/ContactForm'
import Header from '@/components/sections/Header'
import Footer from '@/components/sections/Footer'
import { ClockIcon, TimerIcon, IdeaIcon, LockIcon, DocumentIcon, ChatIcon } from '@/components/icons/CommonIcons'

export default function ContactPage() {
  return (
    <>
      <LoadingScreen />
      <Header />
      <main className="min-h-screen bg-black text-white relative">
        {/* Background Grid Pattern */}
        <div className="fixed inset-0 opacity-10 pointer-events-none">
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="contact-grid" width="40" height="40" patternUnits="userSpaceOnUse">
                <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#contact-grid)" />
          </svg>
        </div>

        {/* Scan Line Effect */}
        <motion.div
          className="fixed inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/5 to-transparent pointer-events-none"
          animate={{ y: ['-100%', '200%'] }}
          transition={{ duration: 8, repeat: Infinity, ease: 'linear' }}
        />

        {/* Hero Section */}
        <section className="relative pt-32 pb-16 px-6 md:px-12 lg:px-24">
          <div className="container mx-auto max-w-7xl relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              {/* Kicker */}
              <div className="font-mono text-xs text-[#78C4D4] border-l-4 border-[#78C4D4] pl-4 mb-8 uppercase tracking-widest">
                [SECTION_07] CONTACT_INTERFACE
              </div>

              {/* Title */}
              <h1 className="font-mono text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-white tracking-tight">
                {'>'} お問い<span className="text-[#00FF96]">合わせ</span>
              </h1>

              {/* Description */}
              <p className="text-white/70 text-sm md:text-base max-w-3xl font-mono leading-relaxed">
                {'// '}業務課題の相談、システム開発のお見積もりなど
                <br />
                {'// '}お気軽にお問い合わせください
              </p>

              {/* Stats Bar */}
              <div className="mt-8 flex flex-wrap gap-6 font-mono text-xs">
                <div className="flex items-center space-x-2">
                  <motion.span
                    className="text-[#00FF96]"
                    animate={{ opacity: [1, 0.5, 1] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  >
                    ●
                  </motion.span>
                  <span className="text-white/60">RESPONSE: <span className="text-[#00FF96]">2営業日以内</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#78C4D4]">●</span>
                  <span className="text-white/60">NDA: <span className="text-[#78C4D4]">対応可能</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#00C896]">●</span>
                  <span className="text-white/60">CONSULTATION: <span className="text-[#00C896]">無料</span></span>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Contact Section */}
        <section className="relative py-20 px-6 md:px-12 lg:px-24">
          <div className="container mx-auto max-w-6xl">
            <div className="grid lg:grid-cols-3 gap-8">
              {/* Contact Info */}
              <motion.div
                initial={{ opacity: 0, x: -30 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
                className="space-y-6"
              >
                <div className="bg-black border border-[#333] p-6 relative overflow-hidden group hover:border-[#78C4D4] transition-colors duration-300">
                  {/* Corner decorations */}
                  <div className="absolute top-0 left-0 w-3 h-3 border-t-2 border-l-2 border-[#78C4D4] opacity-0 group-hover:opacity-100 transition-opacity" />
                  <div className="absolute top-0 right-0 w-3 h-3 border-t-2 border-r-2 border-[#78C4D4] opacity-0 group-hover:opacity-100 transition-opacity" />

                  <h3 className="font-mono text-sm font-bold mb-4 flex items-center space-x-2 text-[#78C4D4]">
                    <ClockIcon className="w-5 h-5" />
                    <span>[BUSINESS_HOURS]</span>
                  </h3>
                  <p className="font-mono text-sm text-white/80">
                    {'> '}平日 10:00-18:00
                    <br />
                    <span className="text-xs text-white/50">{'  '}// 土日祝日を除く</span>
                  </p>
                </div>

                <div className="bg-black border border-[#333] p-6 relative overflow-hidden group hover:border-[#78C4D4] transition-colors duration-300">
                  <div className="absolute top-0 left-0 w-3 h-3 border-t-2 border-l-2 border-[#78C4D4] opacity-0 group-hover:opacity-100 transition-opacity" />
                  <div className="absolute top-0 right-0 w-3 h-3 border-t-2 border-r-2 border-[#78C4D4] opacity-0 group-hover:opacity-100 transition-opacity" />

                  <h3 className="font-mono text-sm font-bold mb-4 flex items-center space-x-2 text-[#78C4D4]">
                    <TimerIcon className="w-5 h-5" />
                    <span>[RESPONSE_TIME]</span>
                  </h3>
                  <p className="font-mono text-sm text-white/80">
                    {'> '}2営業日以内にご返信
                  </p>
                </div>

                <div className="bg-[#78C4D4]/10 border-2 border-[#78C4D4] p-6 relative overflow-hidden">
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-r from-transparent via-[#78C4D4]/10 to-transparent"
                    animate={{ x: ['-100%', '200%'] }}
                    transition={{ duration: 3, repeat: Infinity, ease: 'linear' }}
                  />
                  <h4 className="font-mono text-sm font-bold mb-3 flex items-center space-x-2 text-[#00FF96] relative z-10">
                    <IdeaIcon className="w-5 h-5" />
                    <span>[WELCOME_INQUIRIES]</span>
                  </h4>
                  <ul className="space-y-2 font-mono text-xs text-white/80 relative z-10">
                    <li>{'> '}課題は明確だが解決策が分からない</li>
                    <li>{'> '}まずは話を聞いてほしい</li>
                    <li>{'> '}予算感を知りたい</li>
                    <li>{'> '}技術的な相談をしたい</li>
                  </ul>
                </div>
              </motion.div>

              {/* Contact Form */}
              <motion.div
                initial={{ opacity: 0, x: 30 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: 0.3 }}
                className="lg:col-span-2"
              >
                <div className="bg-black border-2 border-[#78C4D4] p-8 relative overflow-hidden">
                  {/* Scan line effect on form */}
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/5 to-transparent pointer-events-none"
                    animate={{ y: ['-100%', '100%'] }}
                    transition={{ duration: 4, repeat: Infinity, ease: 'linear' }}
                  />

                  {/* Corner brackets */}
                  <div className="absolute top-0 left-0 w-6 h-6 border-t-2 border-l-2 border-[#00FF96]" />
                  <div className="absolute top-0 right-0 w-6 h-6 border-t-2 border-r-2 border-[#00FF96]" />
                  <div className="absolute bottom-0 left-0 w-6 h-6 border-b-2 border-l-2 border-[#00FF96]" />
                  <div className="absolute bottom-0 right-0 w-6 h-6 border-b-2 border-r-2 border-[#00FF96]" />

                  <h2 className="font-mono text-xl font-bold mb-6 text-[#00FF96] relative z-10">
                    {'<'}CONTACT_FORM{'>'}
                  </h2>
                  <div className="relative z-10">
                    <ContactForm />
                  </div>
                </div>
              </motion.div>
            </div>

            {/* Additional Info */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.5 }}
              className="mt-16 grid md:grid-cols-3 gap-6"
            >
              <div className="bg-black border border-[#333] p-6 text-center relative overflow-hidden group hover:border-[#78C4D4] transition-colors duration-300">
                <motion.div
                  className="absolute inset-0 bg-gradient-to-b from-[#78C4D4]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"
                />
                <div className="flex justify-center mb-3 relative z-10">
                  <LockIcon className="text-[#78C4D4] w-10 h-10" size={40} />
                </div>
                <h3 className="font-mono text-sm font-bold mb-2 text-[#78C4D4] relative z-10">[SECURITY]</h3>
                <p className="font-mono text-xs text-white/70 relative z-10">
                  {'// '}お預かりした情報は厳重に管理し、お問い合わせ対応以外の目的で使用することはありません。
                </p>
              </div>

              <div className="bg-black border border-[#333] p-6 text-center relative overflow-hidden group hover:border-[#78C4D4] transition-colors duration-300">
                <motion.div
                  className="absolute inset-0 bg-gradient-to-b from-[#78C4D4]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"
                />
                <div className="flex justify-center mb-3 relative z-10">
                  <DocumentIcon className="text-[#00FF96] w-10 h-10" size={40} />
                </div>
                <h3 className="font-mono text-sm font-bold mb-2 text-[#00FF96] relative z-10">[NDA_SUPPORT]</h3>
                <p className="font-mono text-xs text-white/70 relative z-10">
                  {'// '}機密性の高い案件については、NDA（秘密保持契約）を締結の上でご相談いただけます。
                </p>
              </div>

              <div className="bg-black border border-[#333] p-6 text-center relative overflow-hidden group hover:border-[#78C4D4] transition-colors duration-300">
                <motion.div
                  className="absolute inset-0 bg-gradient-to-b from-[#78C4D4]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"
                />
                <div className="flex justify-center mb-3 relative z-10">
                  <ChatIcon className="text-[#00C896] w-10 h-10" size={40} />
                </div>
                <h3 className="font-mono text-sm font-bold mb-2 text-[#00C896] relative z-10">[ONLINE_MEETING]</h3>
                <p className="font-mono text-xs text-white/70 relative z-10">
                  {'// '}全国どこからでもオンラインでのお打ち合わせが可能です。
                </p>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Corner Decorations */}
        <div className="fixed top-8 left-8 w-16 h-16 border-t-2 border-l-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed top-8 right-8 w-16 h-16 border-t-2 border-r-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed bottom-8 left-8 w-16 h-16 border-b-2 border-l-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed bottom-8 right-8 w-16 h-16 border-b-2 border-r-2 border-[#78C4D4] opacity-30 pointer-events-none" />
      </main>

      <Footer />
    </>
  )
}
