// Generated by ClaudeCode - お問い合わせメール送信API
import { NextResponse } from 'next/server'
import nodemailer from 'nodemailer'

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const { name, company, email, phone, subject, message } = body

    // バリデーション
    if (!name || !email || !subject || !message) {
      return NextResponse.json(
        { error: '必須項目が入力されていません' },
        { status: 400 }
      )
    }

    // 開発環境チェック or SMTP設定が未完了の場合
    const isDevelopment = process.env.NODE_ENV === 'development' ||
                         !process.env.SMTP_USER ||
                         !process.env.SMTP_PASS

    // 開発環境またはSMTP未設定の場合はメール送信をスキップ
    if (isDevelopment) {
      console.log('📧 [開発環境] お問い合わせフォーム送信内容:')
      console.log('━━━━━━━━━━━━━━━━━━━━')
      console.log('お名前:', name)
      console.log('会社名:', company || '（未入力）')
      console.log('メールアドレス:', email)
      console.log('電話番号:', phone || '（未入力）')
      console.log('お問い合わせ種別:', subject)
      console.log('お問い合わせ内容:', message)
      console.log('━━━━━━━━━━━━━━━━━━━━')

      return NextResponse.json(
        { message: 'メールを送信しました（開発環境）' },
        { status: 200 }
      )
    }

    // 本番環境用: メール送信の設定
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    })

    // メール本文の作成
    const emailContent = `
【3125 LAB お問い合わせフォームより】

━━━━━━━━━━━━━━━━━━━━
■ お名前
━━━━━━━━━━━━━━━━━━━━
${name}

━━━━━━━━━━━━━━━━━━━━
■ 会社名
━━━━━━━━━━━━━━━━━━━━
${company || '（未入力）'}

━━━━━━━━━━━━━━━━━━━━
■ メールアドレス
━━━━━━━━━━━━━━━━━━━━
${email}

━━━━━━━━━━━━━━━━━━━━
■ 電話番号
━━━━━━━━━━━━━━━━━━━━
${phone || '（未入力）'}

━━━━━━━━━━━━━━━━━━━━
■ お問い合わせ種別
━━━━━━━━━━━━━━━━━━━━
${subject}

━━━━━━━━━━━━━━━━━━━━
■ お問い合わせ内容
━━━━━━━━━━━━━━━━━━━━
${message}

━━━━━━━━━━━━━━━━━━━━

※このメールは3125 LAB公式サイトのお問い合わせフォームから自動送信されています。
    `

    // メール送信
    await transporter.sendMail({
      from: process.env.SMTP_FROM || email,
      to: process.env.CONTACT_EMAIL || 'contact@example.com',
      subject: `【お問い合わせ】${subject} - ${name}様`,
      text: emailContent,
      replyTo: email,
    })

    // 自動返信メール（お客様へ）
    const autoReplyContent = `
${name} 様

この度は3125 LABにお問い合わせいただき、誠にありがとうございます。

以下の内容でお問い合わせを承りました。
担当者より2営業日以内にご連絡させていただきます。

━━━━━━━━━━━━━━━━━━━━
■ お問い合わせ種別
━━━━━━━━━━━━━━━━━━━━
${subject}

━━━━━━━━━━━━━━━━━━━━
■ お問い合わせ内容
━━━━━━━━━━━━━━━━━━━━
${message}
━━━━━━━━━━━━━━━━━━━━

今しばらくお待ちくださいませ。

─────────────────────
3125 LAB
Web: https://3125lab.jp
─────────────────────

※このメールは自動送信されています。
このメールに返信いただいても対応できませんのでご了承ください。
    `

    try {
      await transporter.sendMail({
        from: process.env.SMTP_FROM || process.env.CONTACT_EMAIL || 'noreply@example.com',
        to: email,
        subject: '【3125 LAB】お問い合わせを受け付けました',
        text: autoReplyContent,
      })
    } catch (autoReplyError) {
      console.error('自動返信メール送信エラー:', autoReplyError)
      // 自動返信が失敗しても、メインの送信は成功として扱う
    }

    return NextResponse.json(
      { message: 'メールを送信しました' },
      { status: 200 }
    )
  } catch (error) {
    console.error('メール送信エラー:', error)
    return NextResponse.json(
      { error: 'メール送信に失敗しました。時間をおいて再度お試しください。' },
      { status: 500 }
    )
  }
}
