// Generated by ClaudeCode - Home Page (Cyber Style)
'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import LoadingScreen from '@/components/LoadingScreen'
import Header from '@/components/sections/Header'
import Footer from '@/components/sections/Footer'
import ProblemSection from '@/components/sections/ProblemSection'
import SolutionSection from '@/components/sections/SolutionSection'

export default function Home() {
  const works = [
    {
      id: '01',
      title: 'LP制作',
      category: 'Web制作',
      client: 'スタートアップ企業',
      result: 'CVR 2.3倍向上',
    },
    {
      id: '02',
      title: 'HP制作',
      category: 'Web制作',
      client: '中小企業',
      result: '問い合わせ数 3倍増',
    },
    {
      id: '03',
      title: '請求書管理システム',
      category: '業務システム',
      client: '営業代行企業',
      result: '工数 40時間/月 削減',
    },
  ]

  return (
    <>
      <LoadingScreen />
      <Header />

      <main className="min-h-screen bg-black text-white">
        {/* Background Grid Pattern */}
        <div className="fixed inset-0 opacity-10 pointer-events-none">
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="main-grid" width="40" height="40" patternUnits="userSpaceOnUse">
                <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#main-grid)" />
          </svg>
        </div>

        {/* Hero Section */}
        <section className="min-h-screen flex items-center relative overflow-hidden pt-20">
          {/* Scan Line Effect */}
          <motion.div
            className="absolute inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/5 to-transparent pointer-events-none"
            animate={{ y: ['-100%', '200%'] }}
            transition={{ duration: 8, repeat: Infinity, ease: 'linear' }}
          />

          <div className="container mx-auto px-6 md:px-12 lg:px-24 relative z-10">
            <motion.div
              initial={{ opacity: 0, y: -30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8 }}
              className="max-w-5xl space-y-8"
            >
              {/* Kicker */}
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
                className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest inline-block border-l-4 border-[#78C4D4] pl-4"
              >
                [SYSTEM_ONLINE] LAB_INITIALIZED
              </motion.div>

              {/* Main Title */}
              <motion.h1
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.3 }}
                className="font-mono text-4xl md:text-6xl lg:text-7xl font-bold leading-tight tracking-tight"
              >
                {'>'} 業務課題を、
                <br />
                <span className="text-[#00FF96]">実験</span>で仕組みに変える
                <br />
                研究所。
              </motion.h1>

              {/* Description */}
              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.5 }}
                className="text-base md:text-lg text-white/70 leading-relaxed max-w-3xl mx-auto font-mono"
              >
                {'// '}3125 LABは、企業が抱えるニッチな業務課題を実験的に解決する開発スタジオです
                <br />
                {'// '}AI × ローコード × API統合で、高速プロトタイピングを実現
              </motion.p>

              {/* Stats */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.6 }}
                className="flex gap-8 flex-wrap font-mono text-xs"
              >
                <div className="flex items-center space-x-2">
                  <motion.span
                    className="text-[#00FF96]"
                    animate={{ opacity: [1, 0.3, 1] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  >
                    ●
                  </motion.span>
                  <span className="text-white/60">PROJECTS: <span className="text-[#00FF96]">50+</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#78C4D4]">●</span>
                  <span className="text-white/60">CLIENTS: <span className="text-[#78C4D4]">30+</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#00C896]">●</span>
                  <span className="text-white/60">SUCCESS_RATE: <span className="text-[#00C896]">98%</span></span>
                </div>
              </motion.div>

              {/* CTA Button */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, delay: 0.7 }}
              >
                <Link href="/contact">
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    animate={{
                      boxShadow: [
                        '0 0 20px rgba(239, 68, 68, 0.8)',
                        '0 0 40px rgba(239, 68, 68, 0.4)',
                        '0 0 20px rgba(239, 68, 68, 0.8)'
                      ]
                    }}
                    transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                    className="font-mono text-sm px-10 py-5 bg-red-600 hover:bg-red-700 text-white font-bold uppercase tracking-wider border-2 border-red-500 relative overflow-hidden"
                  >
                    <span className="relative z-10 flex items-center gap-2">
                      <span className="text-yellow-300">⚠</span>
                      {'>'} 無料相談を開始
                      <span className="text-yellow-300">⚠</span>
                    </span>
                    <motion.div
                      className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
                      animate={{ x: ['-100%', '200%'] }}
                      transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
                    />
                  </motion.button>
                </Link>
              </motion.div>

              {/* Additional Info */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.8, delay: 0.9 }}
                className="flex gap-6 text-xs font-mono text-white/40 pt-4 flex-wrap"
              >
                <div>RESPONSE: 2営業日以内</div>
                <div>|</div>
                <div>NDA: 対応可能</div>
                <div>|</div>
                <div>CONSULTATION: 無料</div>
              </motion.div>
            </motion.div>
          </div>

          {/* Corner Decorations */}
          <div className="absolute top-8 left-8 w-16 h-16 border-t-2 border-l-2 border-[#78C4D4] opacity-50" />
          <div className="absolute top-8 right-8 w-16 h-16 border-t-2 border-r-2 border-[#78C4D4] opacity-50" />
          <div className="absolute bottom-8 left-8 w-16 h-16 border-b-2 border-l-2 border-[#78C4D4] opacity-50" />
          <div className="absolute bottom-8 right-8 w-16 h-16 border-b-2 border-r-2 border-[#78C4D4] opacity-50" />
        </section>

        {/* Problem & Solution Sections - Original Design */}
        <ProblemSection />
        <SolutionSection />

        {/* Works Section */}
        <section className="relative py-24 px-6 md:px-12 lg:px-24 border-t border-[#333]">
          <div className="container mx-auto max-w-7xl relative z-10">
            {/* Kicker */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-xs text-[#78C4D4] border-l-4 border-[#78C4D4] pl-4 mb-8 uppercase tracking-widest"
            >
              [EXPERIMENT_RESULTS] DATABASE_QUERY
            </motion.div>

            {/* Title */}
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-3xl md:text-5xl font-bold mb-12"
            >
              {'>'} 研究<span className="text-[#00FF96]">成果</span>
            </motion.h2>

            {/* Works Grid */}
            <div className="grid md:grid-cols-3 gap-6">
              {works.map((work, index) => (
                <motion.div
                  key={work.id}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: 0.2 + index * 0.1 }}
                  className="bg-black border border-[#333] hover:border-[#78C4D4] transition-all duration-300 relative overflow-hidden group"
                >
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/10 to-transparent h-[200%] pointer-events-none"
                    animate={{ y: ['-100%', '100%'] }}
                    transition={{ duration: 3, repeat: Infinity, ease: 'linear', delay: index * 0.4 }}
                  />

                  <div className="bg-[#111] border-b border-[#333] px-4 py-3 font-mono text-xs">
                    <div className="flex items-center justify-between">
                      <span className="text-[#00FF96]">[CASE_{work.id}]</span>
                      <span className="text-white/40 uppercase">{work.category}</span>
                    </div>
                  </div>

                  <div className="p-6 relative z-10">
                    <h3 className="font-mono text-xl font-bold text-white mb-4 group-hover:text-[#78C4D4] transition-colors">
                      {'> '}{work.title}
                    </h3>

                    <div className="space-y-2 font-mono text-xs mb-4">
                      <div className="flex justify-between border-b border-[#333] pb-2">
                        <span className="text-white/40">CLIENT:</span>
                        <span className="text-white/80">{work.client}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-white/40">RESULT:</span>
                        <span className="text-[#00FF96]">{work.result}</span>
                      </div>
                    </div>
                  </div>

                  <div className="absolute top-0 right-0 w-8 h-8 border-t-2 border-r-2 border-[#78C4D4] opacity-50" />
                  <div className="absolute bottom-0 left-0 w-8 h-8 border-b-2 border-l-2 border-[#78C4D4] opacity-50" />
                </motion.div>
              ))}
            </div>

            {/* See More Link */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.8 }}
              className="text-center mt-12"
            >
              <Link href="/works">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  animate={{
                    boxShadow: [
                      '0 0 15px rgba(239, 68, 68, 0.6)',
                      '0 0 30px rgba(239, 68, 68, 0.3)',
                      '0 0 15px rgba(239, 68, 68, 0.6)'
                    ]
                  }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                  className="font-mono text-sm px-8 py-4 bg-black border-2 border-red-500 text-red-400 hover:bg-red-900/20 font-bold uppercase tracking-wider relative overflow-hidden"
                >
                  <span className="relative z-10 flex items-center gap-2">
                    <span className="text-yellow-300">⚠</span>
                    {'>'} 全ての実績を見る
                  </span>
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-r from-transparent via-red-500/20 to-transparent"
                    animate={{ x: ['-100%', '200%'] }}
                    transition={{ duration: 2.5, repeat: Infinity, ease: 'linear' }}
                  />
                </motion.button>
              </Link>
            </motion.div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="relative py-24 px-6 md:px-12 lg:px-24 border-t border-[#333]">
          <div className="container mx-auto max-w-4xl relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="bg-black border-2 border-[#78C4D4] p-8 md:p-12 relative overflow-hidden"
            >
              <div className="absolute inset-0 bg-gradient-to-br from-[#78C4D4]/5 via-transparent to-[#00FF96]/5 pointer-events-none" />

              <div className="relative z-10 text-center">
                <div className="font-mono text-xs text-[#78C4D4] mb-4 uppercase tracking-widest">
                  [INQUIRY_SYSTEM] READY
                </div>

                <h3 className="font-mono text-2xl md:text-4xl font-bold mb-4">
                  {'>'} START_YOUR_
                  <span className="text-[#00FF96]">EXPERIMENT</span>
                </h3>

                <p className="text-white/70 text-sm mb-8 font-mono">
                  {'// '}どんな小さな課題でも、まずはご相談ください
                </p>

                <Link href="/contact">
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    animate={{
                      boxShadow: [
                        '0 0 20px rgba(239, 68, 68, 0.8)',
                        '0 0 40px rgba(239, 68, 68, 0.4)',
                        '0 0 20px rgba(239, 68, 68, 0.8)'
                      ]
                    }}
                    transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                    className="font-mono text-sm px-8 py-4 bg-red-600 hover:bg-red-700 text-white font-bold uppercase tracking-wider border-2 border-red-500 relative overflow-hidden"
                  >
                    <span className="relative z-10 flex items-center gap-2">
                      <span className="text-yellow-300">⚠</span>
                      {'>'} 無料相談を開始
                      <span className="text-yellow-300">⚠</span>
                    </span>
                    <motion.div
                      className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
                      animate={{ x: ['-100%', '200%'] }}
                      transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
                    />
                  </motion.button>
                </Link>

                <div className="mt-8 flex justify-center gap-8 font-mono text-xs text-white/60 flex-wrap">
                  <div>RESPONSE: <span className="text-[#78C4D4]">2営業日以内</span></div>
                  <div>NDA: <span className="text-[#00FF96]">対応可能</span></div>
                </div>
              </div>

              <div className="absolute top-4 left-4 w-12 h-12 border-t-2 border-l-2 border-[#78C4D4]" />
              <div className="absolute top-4 right-4 w-12 h-12 border-t-2 border-r-2 border-[#78C4D4]" />
              <div className="absolute bottom-4 left-4 w-12 h-12 border-b-2 border-l-2 border-[#78C4D4]" />
              <div className="absolute bottom-4 right-4 w-12 h-12 border-b-2 border-r-2 border-[#78C4D4]" />
            </motion.div>
          </div>
        </section>
      </main>

      <Footer />
    </>
  )
}
