// Generated by ClaudeCode - お問い合わせフォーム
'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'

interface FormData {
  name: string
  company: string
  email: string
  phone: string
  subject: string
  message: string
}

export default function ContactForm() {
  const [formData, setFormData] = useState<FormData>({
    name: '',
    company: '',
    email: '',
    phone: '',
    subject: '',
    message: '',
  })

  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle')
  const [errorMessage, setErrorMessage] = useState('')

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    })
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setStatus('loading')
    setErrorMessage('')

    try {
      const response = await fetch('/api/contact', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData),
      })

      const data = await response.json()

      if (response.ok) {
        setStatus('success')
        setFormData({
          name: '',
          company: '',
          email: '',
          phone: '',
          subject: '',
          message: '',
        })
      } else {
        setStatus('error')
        setErrorMessage(data.error || '送信に失敗しました')
      }
    } catch (error) {
      setStatus('error')
      setErrorMessage('ネットワークエラーが発生しました')
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Name & Company */}
      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <label htmlFor="name" className="block text-sm font-bold mb-2">
            お名前 <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            id="name"
            name="name"
            value={formData.name}
            onChange={handleChange}
            required
            className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent/20 transition-all"
            placeholder="山田 太郎"
          />
        </div>

        <div>
          <label htmlFor="company" className="block text-sm font-bold mb-2">
            会社名
          </label>
          <input
            type="text"
            id="company"
            name="company"
            value={formData.company}
            onChange={handleChange}
            className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent/20 transition-all"
            placeholder="株式会社◯◯"
          />
        </div>
      </div>

      {/* Email & Phone */}
      <div className="grid md:grid-cols-2 gap-6">
        <div>
          <label htmlFor="email" className="block text-sm font-bold mb-2">
            メールアドレス <span className="text-red-500">*</span>
          </label>
          <input
            type="email"
            id="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            required
            className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent/20 transition-all"
            placeholder="example@example.com"
          />
        </div>

        <div>
          <label htmlFor="phone" className="block text-sm font-bold mb-2">
            電話番号
          </label>
          <input
            type="tel"
            id="phone"
            name="phone"
            value={formData.phone}
            onChange={handleChange}
            className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent/20 transition-all"
            placeholder="090-1234-5678"
          />
        </div>
      </div>

      {/* Subject */}
      <div>
        <label htmlFor="subject" className="block text-sm font-bold mb-2">
          お問い合わせ種別 <span className="text-red-500">*</span>
        </label>
        <select
          id="subject"
          name="subject"
          value={formData.subject}
          onChange={handleChange}
          required
          className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent/20 transition-all"
        >
          <option value="">選択してください</option>
          <option value="LP制作のご相談">LP制作のご相談</option>
          <option value="HP制作のご相談">HP制作のご相談</option>
          <option value="業務システム開発のご相談">業務システム開発のご相談</option>
          <option value="お見積もり依頼">お見積もり依頼</option>
          <option value="その他のお問い合わせ">その他のお問い合わせ</option>
        </select>
      </div>

      {/* Message */}
      <div>
        <label htmlFor="message" className="block text-sm font-bold mb-2">
          お問い合わせ内容 <span className="text-red-500">*</span>
        </label>
        <textarea
          id="message"
          name="message"
          value={formData.message}
          onChange={handleChange}
          required
          rows={6}
          className="w-full px-4 py-3 bg-gray-50 border-2 border-gray-300 rounded-lg focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent/20 transition-all resize-none"
          placeholder="お問い合わせ内容を詳しくご記入ください"
        />
      </div>

      {/* Submit Button */}
      <motion.button
        type="submit"
        disabled={status === 'loading'}
        whileHover={{ scale: status === 'loading' ? 1 : 1.02 }}
        whileTap={{ scale: status === 'loading' ? 1 : 0.98 }}
        animate={status !== 'loading' ? { boxShadow: ['0 0 20px rgba(239, 68, 68, 0.8)', '0 0 40px rgba(239, 68, 68, 0.4)', '0 0 20px rgba(239, 68, 68, 0.8)'] } : {}}
        transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
        className={`w-full py-4 rounded font-mono font-bold uppercase tracking-wider relative overflow-hidden border-2 transition-all duration-300 ${
          status === 'loading'
            ? 'bg-gray-700 border-gray-500 text-gray-400 cursor-not-allowed'
            : 'bg-red-600 border-red-500 text-white hover:bg-red-700 shadow-[0_0_20px_rgba(239,68,68,0.6)] hover:shadow-[0_0_30px_rgba(239,68,68,0.9)]'
        }`}
      >
        <span className="relative z-10 flex items-center justify-center gap-2">
          {status === 'loading' ? (
            <>
              <span className="inline-block w-2 h-2 bg-gray-400 rounded-full animate-pulse"></span>
              送信中...
            </>
          ) : (
            <>
              <span className="text-yellow-300">⚠</span>
              送信する
              <span className="text-yellow-300">⚠</span>
            </>
          )}
        </span>
        {status !== 'loading' && (
          <motion.div
            className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
            animate={{ x: ['-100%', '200%'] }}
            transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
          />
        )}
      </motion.button>

      {/* Success Message */}
      {status === 'success' && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-green-50 border-2 border-green-500 rounded-lg p-4 text-center"
        >
          <p className="text-green-700 font-bold">✓ 送信完了</p>
          <p className="text-sm text-green-600 mt-1">
            お問い合わせありがとうございます。担当者より2営業日以内にご連絡いたします。
          </p>
        </motion.div>
      )}

      {/* Error Message */}
      {status === 'error' && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-red-50 border-2 border-red-500 rounded-lg p-4 text-center"
        >
          <p className="text-red-700 font-bold">✗ 送信失敗</p>
          <p className="text-sm text-red-600 mt-1">{errorMessage}</p>
        </motion.div>
      )}
    </form>
  )
}
