// Generated by ClaudeCode - ローディング画面（サイバーパンク風）
'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { useState, useEffect } from 'react'

export default function LoadingScreen() {
  const [isLoading, setIsLoading] = useState(true)
  const [progress, setProgress] = useState(0)

  useEffect(() => {
    // プログレスバーアニメーション
    const progressInterval = setInterval(() => {
      setProgress((prev) => {
        if (prev >= 100) {
          clearInterval(progressInterval)
          return 100
        }
        return prev + 2
      })
    }, 30)

    // 1.5秒後にローディング終了
    const timer = setTimeout(() => {
      setIsLoading(false)
    }, 1500)

    return () => {
      clearTimeout(timer)
      clearInterval(progressInterval)
    }
  }, [])

  return (
    <AnimatePresence>
      {isLoading && (
        <motion.div
          initial={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.5 }}
          className="fixed inset-0 z-[9999] flex items-center justify-center bg-black"
        >
          {/* Background Grid Pattern */}
          <div className="absolute inset-0 opacity-10">
            <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
              <defs>
                <pattern id="loading-grid" width="40" height="40" patternUnits="userSpaceOnUse">
                  <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
                </pattern>
              </defs>
              <rect width="100%" height="100%" fill="url(#loading-grid)" />
            </svg>
          </div>

          <div className="relative z-10 text-center space-y-8 px-4">
            {/* Logo / Title */}
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="space-y-4"
            >
              <motion.div
                className="font-mono text-4xl md:text-5xl font-bold text-white tracking-tight"
                animate={{
                  textShadow: [
                    '0 0 10px rgba(120, 196, 212, 0.5)',
                    '0 0 20px rgba(120, 196, 212, 0.8)',
                    '0 0 10px rgba(120, 196, 212, 0.5)',
                  ]
                }}
                transition={{ duration: 2, repeat: Infinity }}
              >
                {'<'}3125_LAB{'>'}
              </motion.div>

              <div className="font-mono text-xs text-[#78C4D4] tracking-widest opacity-70">
                AI × SYSTEM R&D
              </div>
            </motion.div>

            {/* System Status */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="space-y-4"
            >
              {/* Status Messages */}
              <div className="font-mono text-sm text-white/70 space-y-2">
                <motion.div
                  animate={{ opacity: [0.5, 1, 0.5] }}
                  transition={{ duration: 1.5, repeat: Infinity }}
                  className="flex items-center justify-center space-x-2"
                >
                  <motion.span
                    className="text-[#00FF96]"
                    animate={{ opacity: [1, 0.3, 1] }}
                    transition={{ duration: 1, repeat: Infinity }}
                  >
                    ⚙
                  </motion.span>
                  <span>INITIALIZING SYSTEM...</span>
                </motion.div>

                <div className="text-[#78C4D4] text-xs">
                  {'>'} LOADING_MODULES: {progress}%
                </div>
              </div>

              {/* Progress Bar */}
              <div className="w-64 md:w-80 mx-auto">
                {/* Bar Container */}
                <div className="relative h-3 border-2 border-[#333] bg-black overflow-hidden">
                  {/* Progress Fill */}
                  <motion.div
                    className="absolute inset-y-0 left-0 bg-gradient-to-r from-[#78C4D4] via-[#00FF96] to-[#00C896]"
                    style={{ width: `${progress}%` }}
                  />

                  {/* Scan Line Effect */}
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent"
                    animate={{ x: ['-100%', '200%'] }}
                    transition={{ duration: 1.5, repeat: Infinity, ease: 'linear' }}
                    style={{ width: '30%' }}
                  />
                </div>

                {/* Corner Brackets */}
                <div className="relative mt-2">
                  <div className="absolute -top-5 -left-2 w-4 h-4 border-t-2 border-l-2 border-[#78C4D4]" />
                  <div className="absolute -top-5 -right-2 w-4 h-4 border-t-2 border-r-2 border-[#78C4D4]" />
                </div>
              </div>

              {/* System Indicators */}
              <div className="flex justify-center gap-6 font-mono text-[10px] text-white/40 pt-4">
                <div className="flex items-center space-x-1">
                  <motion.span
                    className="text-[#00FF96]"
                    animate={{ opacity: [1, 0.3, 1] }}
                    transition={{ duration: 1, repeat: Infinity }}
                  >
                    ●
                  </motion.span>
                  <span>CORE: ONLINE</span>
                </div>
                <div className="flex items-center space-x-1">
                  <motion.span
                    className="text-[#78C4D4]"
                    animate={{ opacity: [1, 0.3, 1] }}
                    transition={{ duration: 1.2, repeat: Infinity, delay: 0.2 }}
                  >
                    ●
                  </motion.span>
                  <span>DB: CONNECTED</span>
                </div>
                <div className="flex items-center space-x-1">
                  <motion.span
                    className="text-[#00C896]"
                    animate={{ opacity: [1, 0.3, 1] }}
                    transition={{ duration: 0.8, repeat: Infinity, delay: 0.4 }}
                  >
                    ●
                  </motion.span>
                  <span>API: READY</span>
                </div>
              </div>
            </motion.div>

            {/* Loading Dots Animation */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.6, delay: 0.5 }}
              className="flex justify-center space-x-2"
            >
              {[0, 1, 2, 3].map((i) => (
                <motion.div
                  key={i}
                  className="w-2 h-2 bg-[#78C4D4]"
                  animate={{
                    opacity: [0.3, 1, 0.3],
                    scale: [0.8, 1.2, 0.8],
                  }}
                  transition={{
                    duration: 1.5,
                    repeat: Infinity,
                    delay: i * 0.2,
                  }}
                />
              ))}
            </motion.div>
          </div>

          {/* Corner Decorations */}
          <div className="absolute top-8 left-8 w-16 h-16 border-t-2 border-l-2 border-[#78C4D4] opacity-50" />
          <div className="absolute top-8 right-8 w-16 h-16 border-t-2 border-r-2 border-[#78C4D4] opacity-50" />
          <div className="absolute bottom-8 left-8 w-16 h-16 border-b-2 border-l-2 border-[#78C4D4] opacity-50" />
          <div className="absolute bottom-8 right-8 w-16 h-16 border-b-2 border-r-2 border-[#78C4D4] opacity-50" />
        </motion.div>
      )}
    </AnimatePresence>
  )
}
