// Generated by ClaudeCode - ビーカーの中にコードが流れ込むアニメーション
'use client'

import { motion } from 'framer-motion'

export default function BeakerCode() {
  return (
    <svg viewBox="0 0 300 350" className="w-full h-auto" xmlns="http://www.w3.org/2000/svg">
      {/* Beaker */}
      <defs>
        <linearGradient id="liquidGradient" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stopColor="#78C4D4" stopOpacity="0.3" />
          <stop offset="100%" stopColor="#78C4D4" stopOpacity="0.7" />
        </linearGradient>
      </defs>

      {/* Beaker body */}
      <path
        d="M 100 80 L 100 150 L 80 280 Q 80 300 100 300 L 200 300 Q 220 300 220 280 L 200 150 L 200 80 Z"
        fill="transparent"
        stroke="#000000"
        strokeWidth="3"
      />

      {/* Beaker rim */}
      <rect x="90" y="70" width="120" height="10" fill="#000000" />

      {/* Liquid */}
      <motion.path
        d="M 100 200 L 85 280 Q 85 295 100 295 L 200 295 Q 215 295 215 280 L 200 200 Z"
        fill="url(#liquidGradient)"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 1, delay: 0.3 }}
      />

      {/* Measurement lines */}
      <line x1="85" y1="200" x2="95" y2="200" stroke="#000000" strokeWidth="1.5" />
      <line x1="85" y1="240" x2="95" y2="240" stroke="#000000" strokeWidth="1.5" />
      <line x1="85" y1="280" x2="95" y2="280" stroke="#000000" strokeWidth="1.5" />

      {/* Code snippets falling in - animated */}
      <motion.g
        initial={{ y: -50, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.8, delay: 0.2 }}
      >
        <text x="110" y="30" fontSize="14" fontFamily="monospace" fill="#000000">{'<div>'}</text>
      </motion.g>

      <motion.g
        initial={{ y: -50, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.8, delay: 0.4 }}
      >
        <text x="140" y="50" fontSize="12" fontFamily="monospace" fill="#78C4D4">{'AI()'}</text>
      </motion.g>

      <motion.g
        initial={{ y: -50, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ duration: 0.8, delay: 0.6 }}
      >
        <text x="95" y="65" fontSize="11" fontFamily="monospace" fill="#000000">{'function'}</text>
      </motion.g>

      {/* Code symbols in liquid - dots style */}
      <motion.g
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 0.6, y: 0 }}
        transition={{ duration: 1, delay: 0.8 }}
      >
        <text x="120" y="220" fontSize="20" fontFamily="monospace" fill="#000000" opacity="0.3">{'{}'}</text>
        <text x="160" y="240" fontSize="18" fontFamily="monospace" fill="#000000" opacity="0.3">{'[]'}</text>
        <text x="110" y="260" fontSize="16" fontFamily="monospace" fill="#000000" opacity="0.3">{'()'}</text>
        <text x="170" y="270" fontSize="14" fontFamily="monospace" fill="#000000" opacity="0.3">{'<>'}</text>
      </motion.g>

      {/* Bubbles rising */}
      {[0, 1, 2, 3].map((i) => (
        <motion.circle
          key={i}
          cx={120 + i * 20}
          cy={280}
          r={4}
          fill="#FFFFFF"
          opacity="0.5"
          animate={{
            y: [-20, -60],
            opacity: [0.5, 0],
          }}
          transition={{
            duration: 2,
            delay: i * 0.3,
            repeat: Infinity,
            repeatDelay: 0.5,
          }}
        />
      ))}
    </svg>
  )
}
