// Generated by ClaudeCode - デスク上でフラスコを覗く人物
'use client'

export default function DeskScientist() {
  return (
    <svg viewBox="0 0 300 280" className="w-full h-auto" xmlns="http://www.w3.org/2000/svg">
      {/* Desk */}
      <rect x="30" y="160" width="240" height="8" fill="#000000" />
      <rect x="40" y="168" width="8" height="80" fill="#000000" />
      <rect x="252" y="168" width="8" height="80" fill="#000000" />

      {/* Flask on desk */}
      <g>
        {/* Flask body */}
        <circle cx="180" cy="140" r="25" fill="transparent" stroke="#000000" strokeWidth="2.5" />
        <rect x="175" y="95" width="10" height="20" fill="transparent" stroke="#000000" strokeWidth="2.5" />
        <path d="M 175 115 Q 165 125 155 140 Q 155 145 160 145 L 200 145 Q 205 145 205 140 Q 195 125 185 115" fill="transparent" stroke="#000000" strokeWidth="2.5" />

        {/* Liquid in flask */}
        <circle cx="180" cy="140" r="22" fill="#78C4D4" opacity="0.4" />

        {/* Flask opening */}
        <rect x="173" y="90" width="14" height="5" fill="#000000" />

        {/* Bubbles */}
        <circle cx="175" cy="135" r="3" fill="#FFFFFF" opacity="0.7" />
        <circle cx="185" cy="142" r="2.5" fill="#FFFFFF" opacity="0.7" />
        <circle cx="178" cy="145" r="2" fill="#FFFFFF" opacity="0.7" />
      </g>

      {/* Person leaning over to look at flask */}
      <g>
        {/* Head */}
        <circle cx="120" cy="100" r="20" fill="#FFD4A3" stroke="#000000" strokeWidth="2" />

        {/* Eyes looking at flask */}
        <circle cx="115" cy="98" r="2.5" fill="#000000" />
        <circle cx="125" cy="98" r="2.5" fill="#000000" />

        {/* Focused expression */}
        <path d="M 113 108 Q 120 106 127 108" stroke="#000000" strokeWidth="1.5" fill="none" />

        {/* Lab coat body - leaning */}
        <path d="M 110 120 L 105 160 L 135 160 L 130 120" fill="#FFFFFF" stroke="#000000" strokeWidth="2" />

        {/* Arm reaching toward flask */}
        <path d="M 130 130 Q 150 125 170 130" stroke="#FFFFFF" strokeWidth="7" />
        <path d="M 130 130 Q 150 125 170 130" stroke="#000000" strokeWidth="2" fill="none" />

        {/* Hand near flask */}
        <circle cx="170" cy="130" r="6" fill="#FFD4A3" stroke="#000000" strokeWidth="1.5" />
      </g>

      {/* Book on desk */}
      <g>
        <rect x="60" y="140" width="40" height="28" fill="#78C4D4" stroke="#000000" strokeWidth="2" />
        <line x1="65" y1="148" x2="95" y2="148" stroke="#000000" strokeWidth="1" strokeDasharray="2 1" />
        <line x1="65" y1="154" x2="95" y2="154" stroke="#000000" strokeWidth="1" strokeDasharray="2 1" />
        <line x1="65" y1="160" x2="95" y2="160" stroke="#000000" strokeWidth="1" strokeDasharray="2 1" />
      </g>

      {/* Pencil on desk */}
      <g>
        <rect x="220" y="150" width="35" height="4" fill="#FFD4A3" stroke="#000000" strokeWidth="1" />
        <polygon points="255,148 265,152 255,156" fill="#000000" />
        <rect x="218" y="149" width="4" height="6" fill="#FFD4A3" stroke="#000000" strokeWidth="1" />
      </g>

      {/* Research notes */}
      <g opacity="0.9" transform="rotate(15 235 125)">
        <rect x="215" y="110" width="40" height="30" fill="#FFFFFF" stroke="#000000" strokeWidth="1.5" />
        <line x1="220" y1="118" x2="250" y2="118" stroke="#000000" strokeWidth="0.8" strokeDasharray="2 1" />
        <line x1="220" y1="124" x2="250" y2="124" stroke="#78C4D4" strokeWidth="0.8" strokeDasharray="2 1" />
        <line x1="220" y1="130" x2="245" y2="130" stroke="#000000" strokeWidth="0.8" strokeDasharray="2 1" />
      </g>
    </svg>
  )
}
