// Generated by ClaudeCode - ラボで白衣を着た人がPCを操作するドット調イラスト
'use client'

export default function LabScientist() {
  return (
    <svg viewBox="0 0 400 300" className="w-full h-auto" xmlns="http://www.w3.org/2000/svg">
      {/* Background grid pattern */}
      <defs>
        <pattern id="dotPattern" x="0" y="0" width="10" height="10" patternUnits="userSpaceOnUse">
          <circle cx="1" cy="1" r="1" fill="#78C4D4" opacity="0.2" />
        </pattern>
      </defs>
      <rect width="400" height="300" fill="url(#dotPattern)" />

      {/* Desk */}
      <rect x="50" y="180" width="300" height="8" fill="#000000" />
      <rect x="60" y="188" width="10" height="80" fill="#000000" />
      <rect x="330" y="188" width="10" height="80" fill="#000000" />

      {/* Computer monitor */}
      <rect x="120" y="120" width="120" height="80" fill="#78C4D4" stroke="#000000" strokeWidth="3" />
      <rect x="130" y="130" width="100" height="60" fill="#FFFFFF" />

      {/* Code on screen - dot style */}
      <line x1="140" y1="140" x2="180" y2="140" stroke="#78C4D4" strokeWidth="2" strokeDasharray="4 2" />
      <line x1="140" y1="150" x2="210" y2="150" stroke="#000000" strokeWidth="2" strokeDasharray="4 2" />
      <line x1="140" y1="160" x2="190" y2="160" stroke="#78C4D4" strokeWidth="2" strokeDasharray="4 2" />
      <line x1="140" y1="170" x2="200" y2="170" stroke="#000000" strokeWidth="2" strokeDasharray="4 2" />

      {/* Monitor stand */}
      <rect x="170" y="200" width="20" height="30" fill="#000000" />
      <rect x="150" y="220" width="60" height="8" fill="#000000" />

      {/* Person - dot style body */}
      <circle cx="280" cy="120" r="20" fill="#FFD4A3" stroke="#000000" strokeWidth="2" />

      {/* Lab coat - white */}
      <rect x="260" y="140" width="40" height="60" fill="#FFFFFF" stroke="#000000" strokeWidth="2" />

      {/* Arms */}
      <line x1="260" y1="150" x2="220" y2="170" stroke="#FFFFFF" strokeWidth="8" />
      <line x1="260" y1="150" x2="220" y2="170" stroke="#000000" strokeWidth="2" />

      <line x1="300" y1="150" x2="250" y2="140" stroke="#FFD4A3" strokeWidth="6" />
      <line x1="300" y1="150" x2="250" y2="140" stroke="#000000" strokeWidth="1.5" />

      {/* Hand on keyboard area */}
      <circle cx="250" cy="140" r="5" fill="#FFD4A3" stroke="#000000" strokeWidth="1" />

      {/* Beaker on desk */}
      <path d="M 310 150 L 320 180 L 340 180 L 350 150 Z" fill="transparent" stroke="#000000" strokeWidth="2" />
      <rect x="310" y="145" width="40" height="5" fill="#000000" />
      <path d="M 315 160 L 318 178 L 342 178 L 345 160" fill="#78C4D4" opacity="0.4" />

      {/* Bubbles in beaker */}
      <circle cx="325" cy="165" r="3" fill="#FFFFFF" opacity="0.6" />
      <circle cx="335" cy="170" r="2" fill="#FFFFFF" opacity="0.6" />
      <circle cx="328" cy="173" r="2.5" fill="#FFFFFF" opacity="0.6" />
    </svg>
  )
}
