// Generated by ClaudeCode - 書類が山積みで困っているオフィスワーカー
'use client'

export default function OfficeWorker() {
  return (
    <svg viewBox="0 0 300 250" className="w-full h-auto" xmlns="http://www.w3.org/2000/svg">
      {/* Desk */}
      <rect x="30" y="150" width="240" height="6" fill="#000000" />

      {/* Papers stack 1 */}
      <g opacity="0.9">
        <rect x="50" y="110" width="40" height="50" fill="#FFFFFF" stroke="#000000" strokeWidth="2" />
        <line x1="55" y1="120" x2="85" y2="120" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
        <line x1="55" y1="130" x2="85" y2="130" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
        <line x1="55" y1="140" x2="85" y2="140" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
      </g>

      {/* Papers stack 2 - tilted */}
      <g opacity="0.9" transform="rotate(-10 115 125)">
        <rect x="95" y="100" width="40" height="55" fill="#FFFFFF" stroke="#000000" strokeWidth="2" />
        <line x1="100" y1="110" x2="130" y2="110" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
        <line x1="100" y1="120" x2="130" y2="120" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
      </g>

      {/* Papers stack 3 */}
      <g opacity="0.9">
        <rect x="200" y="105" width="45" height="55" fill="#FFFFFF" stroke="#000000" strokeWidth="2" />
        <line x1="205" y1="115" x2="240" y2="115" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
        <line x1="205" y1="125" x2="240" y2="125" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
        <line x1="205" y1="135" x2="240" y2="135" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
        <line x1="205" y1="145" x2="240" y2="145" stroke="#000000" strokeWidth="1" strokeDasharray="2 2" />
      </g>

      {/* Person - stressed */}
      <circle cx="150" cy="90" r="18" fill="#FFD4A3" stroke="#000000" strokeWidth="2" />

      {/* Stressed face */}
      <circle cx="145" cy="87" r="2" fill="#000000" />
      <circle cx="155" cy="87" r="2" fill="#000000" />
      <path d="M 142 100 Q 150 95 158 100" stroke="#000000" strokeWidth="2" fill="none" />

      {/* Stress marks */}
      <line x1="130" y1="75" x2="125" y2="70" stroke="#000000" strokeWidth="2" />
      <line x1="133" y1="80" x2="128" y2="78" stroke="#000000" strokeWidth="2" />
      <line x1="170" y1="75" x2="175" y2="70" stroke="#000000" strokeWidth="2" />
      <line x1="167" y1="80" x2="172" y2="78" stroke="#000000" strokeWidth="2" />

      {/* Body */}
      <rect x="135" y="108" width="30" height="45" fill="#78C4D4" stroke="#000000" strokeWidth="2" />

      {/* Arms raised in frustration */}
      <line x1="135" y1="115" x2="110" y2="100" stroke="#FFD4A3" strokeWidth="6" />
      <line x1="135" y1="115" x2="110" y2="100" stroke="#000000" strokeWidth="1.5" />

      <line x1="165" y1="115" x2="190" y2="100" stroke="#FFD4A3" strokeWidth="6" />
      <line x1="165" y1="115" x2="190" y2="100" stroke="#000000" strokeWidth="1.5" />

      {/* Hands */}
      <circle cx="110" cy="100" r="5" fill="#FFD4A3" stroke="#000000" strokeWidth="1" />
      <circle cx="190" cy="100" r="5" fill="#FFD4A3" stroke="#000000" strokeWidth="1" />
    </svg>
  )
}
