// Generated by ClaudeCode - ホワイトボードを囲む人々
'use client'

export default function Whiteboard() {
  return (
    <svg viewBox="0 0 400 300" className="w-full h-auto" xmlns="http://www.w3.org/2000/svg">
      {/* Whiteboard */}
      <rect x="80" y="30" width="240" height="160" fill="#FFFFFF" stroke="#000000" strokeWidth="3" rx="4" />

      {/* Whiteboard content - sketch style */}
      <g strokeDasharray="4 2">
        {/* Title */}
        <line x1="100" y1="50" x2="180" y2="50" stroke="#000000" strokeWidth="2.5" />

        {/* Boxes representing cases */}
        <rect x="100" y="70" width="60" height="50" fill="transparent" stroke="#78C4D4" strokeWidth="2" />
        <text x="115" y="100" fontSize="12" fill="#000000">Case</text>
        <text x="118" y="112" fontSize="10" fill="#78C4D4">01</text>

        <rect x="180" y="70" width="60" height="50" fill="transparent" stroke="#78C4D4" strokeWidth="2" />
        <text x="195" y="100" fontSize="12" fill="#000000">Case</text>
        <text x="198" y="112" fontSize="10" fill="#78C4D4">02</text>

        <rect x="260" y="70" width="50" height="50" fill="transparent" stroke="#78C4D4" strokeWidth="2" />
        <text x="270" y="100" fontSize="12" fill="#000000">Case</text>
        <text x="273" y="112" fontSize="10" fill="#78C4D4">03</text>

        {/* Flow arrows */}
        <path d="M 130 130 L 130 145" stroke="#000000" strokeWidth="2" markerEnd="url(#arrowhead)" />
        <path d="M 210 130 L 210 145" stroke="#000000" strokeWidth="2" markerEnd="url(#arrowhead)" />

        {/* Result box */}
        <rect x="100" y="145" width="140" height="35" fill="transparent" stroke="#000000" strokeWidth="2" />
        <line x1="110" y1="155" x2="180" y2="155" stroke="#78C4D4" strokeWidth="1.5" strokeDasharray="3 2" />
        <line x1="110" y1="165" x2="220" y2="165" stroke="#78C4D4" strokeWidth="1.5" strokeDasharray="3 2" />
        <line x1="110" y1="175" x2="200" y2="175" stroke="#78C4D4" strokeWidth="1.5" strokeDasharray="3 2" />
      </g>

      {/* Arrow marker definition */}
      <defs>
        <marker id="arrowhead" markerWidth="10" markerHeight="10" refX="5" refY="3" orient="auto">
          <polygon points="0 0, 6 3, 0 6" fill="#000000" />
        </marker>
      </defs>

      {/* Person 1 - left */}
      <g>
        <circle cx="40" cy="140" r="15" fill="#FFD4A3" stroke="#000000" strokeWidth="2" />
        <rect x="28" y="155" width="24" height="35" fill="#78C4D4" stroke="#000000" strokeWidth="2" />

        {/* Pointing arm */}
        <line x1="52" y1="165" x2="80" y2="120" stroke="#FFD4A3" strokeWidth="5" />
        <line x1="52" y1="165" x2="80" y2="120" stroke="#000000" strokeWidth="1.5" />
        <circle cx="80" cy="120" r="4" fill="#FFD4A3" stroke="#000000" strokeWidth="1" />
      </g>

      {/* Person 2 - right */}
      <g>
        <circle cx="360" cy="140" r="15" fill="#FFD4A3" stroke="#000000" strokeWidth="2" />
        <rect x="348" y="155" width="24" height="35" fill="#000000" stroke="#000000" strokeWidth="2" />

        {/* Crossed arms */}
        <line x1="348" y1="165" x2="360" y2="175" stroke="#FFD4A3" strokeWidth="5" />
        <line x1="372" y1="165" x2="360" y2="175" stroke="#FFD4A3" strokeWidth="5" />
        <line x1="348" y1="165" x2="360" y2="175" stroke="#000000" strokeWidth="1.5" />
        <line x1="372" y1="165" x2="360" y2="175" stroke="#000000" strokeWidth="1.5" />
      </g>

      {/* Person 3 - center front */}
      <g>
        <circle cx="200" cy="230" r="18" fill="#FFD4A3" stroke="#000000" strokeWidth="2" />
        <rect x="185" y="248" width="30" height="40" fill="#FFFFFF" stroke="#000000" strokeWidth="2" />

        {/* Arms at sides */}
        <line x1="185" y1="258" x2="165" y2="270" stroke="#FFFFFF" strokeWidth="6" />
        <line x1="215" y1="258" x2="235" y2="270" stroke="#FFFFFF" strokeWidth="6" />
        <line x1="185" y1="258" x2="165" y2="270" stroke="#000000" strokeWidth="1.5" />
        <line x1="215" y1="258" x2="235" y2="270" stroke="#000000" strokeWidth="1.5" />
      </g>

      {/* Thought bubble from center person */}
      <circle cx="240" cy="215" r="6" fill="#FFFFFF" stroke="#000000" strokeWidth="1.5" />
      <circle cx="250" cy="205" r="4" fill="#FFFFFF" stroke="#000000" strokeWidth="1.5" />
      <ellipse cx="270" cy="190" rx="20" ry="15" fill="#FFFFFF" stroke="#000000" strokeWidth="2" />
      <text x="260" y="195" fontSize="16" fill="#000000">💡</text>
    </svg>
  )
}
