// Generated by ClaudeCode - Research Page (Cyber Style)
'use client'

import { motion } from 'framer-motion'
import LoadingScreen from '@/components/LoadingScreen'
import Header from '@/components/sections/Header'
import Footer from '@/components/sections/Footer'

export default function ResearchPage() {
  const labs = [
    {
      number: '01',
      name: 'AI_LAB',
      icon: '[AI]',
      description: 'ChatGPT APIやOCR技術を活用した自動化ソリューションの研究開発',
      focus: ['自然言語処理', 'OCR/文字認識', 'データ分類・抽出'],
    },
    {
      number: '02',
      name: 'LOW_CODE_LAB',
      icon: '[LC]',
      description: 'Airtable、Zapier、GASなどを組み合わせた高速プロトタイピング',
      focus: ['ノーコード/ローコード', 'ワークフロー自動化', 'データベース設計'],
    },
    {
      number: '03',
      name: 'INTEGRATION_LAB',
      icon: '[INT]',
      description: '既存SaaSとのAPI連携によるデータ統合・一元管理',
      focus: ['API統合', 'Webhook連携', 'データ同期'],
    },
    {
      number: '04',
      name: 'WEB_LAB',
      icon: '[WEB]',
      description: 'Next.js、React、Tailwind CSSを用いたモダンWeb開発',
      focus: ['フロントエンド開発', 'UI/UXデザイン', 'レスポンシブ対応'],
    },
    {
      number: '05',
      name: 'DATA_LAB',
      icon: '[DAT]',
      description: 'データ分析・可視化によるビジネスインサイトの抽出',
      focus: ['データ分析', 'ダッシュボード構築', 'レポート自動化'],
    },
    {
      number: '06',
      name: 'SECURITY_LAB',
      icon: '[SEC]',
      description: 'セキュアな業務システム構築とデータ保護の実践',
      focus: ['認証・認可', 'データ暗号化', 'セキュリティ監査'],
    },
  ]

  const methods = [
    {
      number: '01',
      title: '課題の深掘り',
      description: '業務フローを詳細にヒアリングし、本質的な課題を特定します。表面的な要望ではなく、根本的な問題解決を目指します。',
    },
    {
      number: '02',
      title: '仮説の構築',
      description: '技術的なアプローチを複数検討し、最適な解決策の仮説を立てます。コスト、期間、効果を総合的に評価します。',
    },
    {
      number: '03',
      title: 'プロトタイプ開発',
      description: '小さく早く試作し、実際に触って検証できる環境を構築。フィードバックを即座に反映します。',
    },
    {
      number: '04',
      title: '実験と改善',
      description: '実運用を想定したテストを繰り返し、使い勝手やパフォーマンスを改善。PDCAサイクルを高速で回します。',
    },
    {
      number: '05',
      title: '本番導入・保守',
      description: 'スムーズに業務へ導入し、運用後も継続的にサポート。ビジネスの変化に合わせてアップデートします。',
    },
  ]

  return (
    <>
      <LoadingScreen />
      <Header />

      <main className="min-h-screen bg-black text-white relative">
        {/* Background Grid Pattern */}
        <div className="fixed inset-0 opacity-10 pointer-events-none">
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="research-grid" width="40" height="40" patternUnits="userSpaceOnUse">
                <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#research-grid)" />
          </svg>
        </div>

        {/* Scan Line Effect */}
        <motion.div
          className="fixed inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/5 to-transparent pointer-events-none"
          animate={{ y: ['-100%', '200%'] }}
          transition={{ duration: 8, repeat: Infinity, ease: 'linear' }}
        />

        {/* Hero Section */}
        <section className="relative pt-32 pb-16 px-6 md:px-12 lg:px-24">
          <div className="container mx-auto max-w-7xl relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              {/* Kicker */}
              <div className="font-mono text-xs text-[#78C4D4] border-l-4 border-[#78C4D4] pl-4 mb-8 uppercase tracking-widest">
                [RESEARCH_LAB] METHODOLOGY_ARCHIVE
              </div>

              {/* Title */}
              <h1 className="font-mono text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-white tracking-tight">
                {'>'} EXPERIMENTAL_
                <span className="text-[#00FF96]">APPROACH</span>
              </h1>

              {/* Description */}
              <p className="text-white/70 text-sm md:text-base max-w-3xl font-mono leading-relaxed">
                {'// '}6つの専門ラボと独自の研究手法で業務課題を科学的に解決
                <br />
                {'// '}実験的アプローチによる確実な成果創出
              </p>

              {/* Stats Bar */}
              <div className="mt-8 flex flex-wrap gap-6 font-mono text-xs">
                <div className="flex items-center space-x-2">
                  <motion.span
                    className="text-[#00FF96]"
                    animate={{ opacity: [1, 0.5, 1] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  >
                    ●
                  </motion.span>
                  <span className="text-white/60">METHODOLOGY: <span className="text-[#00FF96]">06_LABS</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#78C4D4]">●</span>
                  <span className="text-white/60">APPROACH: <span className="text-[#78C4D4]">EXPERIMENTAL</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#00C896]">●</span>
                  <span className="text-white/60">STATUS: <span className="text-[#00C896]">ACTIVE</span></span>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Research Philosophy */}
        <section className="relative py-20 px-6 md:px-12 lg:px-24">
          <div className="container mx-auto max-w-6xl">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest border-l-4 border-[#78C4D4] pl-4 mb-8 inline-block"
            >
              [SECTION_02] PHILOSOPHY
            </motion.div>

            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-3xl md:text-4xl lg:text-5xl font-bold mb-6"
            >
              {'<'}RESEARCH_PHILOSOPHY{'>'}
              <br />
              <span className="text-[#00FF96]">// 研究理念</span>
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="font-mono text-sm text-white/70 mb-12"
            >
              {'> '}私たちの研究開発における3つの原則
            </motion.p>

            <div className="grid md:grid-cols-3 gap-6">
              {[
                {
                  icon: '[SML]',
                  title: 'START_SMALL',
                  subtitle: '小さく始める',
                  description: '最初から完璧を目指さず、最小限の機能で素早くリリース。実際に使いながら改善していきます。',
                },
                {
                  icon: '[EXP]',
                  title: 'EXPERIMENTAL',
                  subtitle: '実験的思考',
                  description: '仮説を立て、検証し、学習する。失敗を恐れず、高速でPDCAサイクルを回します。',
                },
                {
                  icon: '[FLD]',
                  title: 'FIELD_FOCUSED',
                  subtitle: '現場主義',
                  description: '実際の業務現場に寄り添い、使う人の視点で開発。机上の空論ではなく、実践的なソリューションを提供します。',
                },
              ].map((principle, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: 0.3 + index * 0.1 }}
                  className="bg-black border border-[#333] p-6 relative overflow-hidden group hover:border-[#78C4D4] transition-all duration-300"
                >
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-b from-[#78C4D4]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"
                  />
                  <div className="font-mono text-4xl font-bold mb-4 relative z-10 text-[#00FF96]">{principle.icon}</div>
                  <h3 className="font-mono text-sm font-bold mb-1 text-[#78C4D4] relative z-10">[{principle.title}]</h3>
                  <h4 className="text-xl font-bold mb-3 relative z-10">{principle.subtitle}</h4>
                  <p className="font-mono text-xs text-white/70 leading-relaxed relative z-10">{'// '}{principle.description}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Research Labs */}
        <section className="relative py-20 px-6 md:px-12 lg:px-24 border-t border-[#333]">
          <div className="container mx-auto max-w-6xl">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest border-l-4 border-[#78C4D4] pl-4 mb-8 inline-block"
            >
              [SECTION_03] RESEARCH_LABS
            </motion.div>

            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-3xl md:text-4xl lg:text-5xl font-bold mb-6"
            >
              {'<'}LABS{'>'} <span className="text-[#00FF96]">// 研究領域</span>
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="font-mono text-sm text-white/70 mb-12"
            >
              {'> '}6つの専門ラボで、多様な技術課題に対応します。
            </motion.p>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {labs.map((lab, index) => (
                <motion.div
                  key={lab.number}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="bg-black border border-[#333] p-6 relative overflow-hidden group hover:border-[#78C4D4] transition-all duration-300"
                >
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-b from-[#78C4D4]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"
                  />

                  <div className="flex items-center justify-between mb-4 relative z-10">
                    <div className="font-mono text-4xl font-bold text-[#00FF96]">{lab.icon}</div>
                    <div className="font-mono text-xs text-[#00FF96] border border-[#00FF96] px-2 py-1">
                      LAB_{lab.number}
                    </div>
                  </div>

                  <h3 className="font-mono text-lg font-bold mb-3 text-[#78C4D4] relative z-10">{lab.name}</h3>
                  <p className="font-mono text-xs text-white/70 leading-relaxed mb-4 relative z-10">{'// '}{lab.description}</p>

                  <div className="border-t border-[#333] pt-4 relative z-10">
                    <div className="font-mono text-xs text-[#00FF96] mb-2">[FOCUS_AREAS]</div>
                    <ul className="space-y-1">
                      {lab.focus.map((item, i) => (
                        <li key={i} className="font-mono text-xs text-white/60 flex items-center gap-2">
                          <span className="w-1 h-1 bg-[#00FF96] rounded-full" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Corner decorations */}
                  <div className="absolute top-0 right-0 w-4 h-4 border-t border-r border-[#78C4D4] opacity-30" />
                  <div className="absolute bottom-0 left-0 w-4 h-4 border-b border-l border-[#78C4D4] opacity-30" />
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Method */}
        <section className="relative py-20 px-6 md:px-12 lg:px-24 border-t border-[#333]">
          <div className="container mx-auto max-w-6xl">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest border-l-4 border-[#78C4D4] pl-4 mb-8 inline-block"
            >
              [SECTION_04] METHOD
            </motion.div>

            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-3xl md:text-4xl lg:text-5xl font-bold mb-6"
            >
              {'<'}METHOD{'>'} <span className="text-[#00FF96]">// 研究手法</span>
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="font-mono text-sm text-white/70 mb-12"
            >
              {'> '}5つのステップで、確実に成果を実現します。
            </motion.p>

            <div className="space-y-4">
              {methods.map((method, index) => (
                <motion.div
                  key={method.number}
                  initial={{ opacity: 0, x: -30 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="bg-black border border-[#333] p-6 relative overflow-hidden group hover:border-[#78C4D4] transition-all duration-300"
                >
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-r from-transparent via-[#78C4D4]/5 to-transparent pointer-events-none"
                    animate={{ x: ['-100%', '200%'] }}
                    transition={{ duration: 3, repeat: Infinity, ease: 'linear', delay: index * 0.5 }}
                  />
                  <div className="flex items-start gap-4 relative z-10">
                    <div className="flex-shrink-0 w-12 h-12 bg-[#00FF96] text-black font-mono font-bold text-lg flex items-center justify-center border-2 border-[#00C896]">
                      {method.number}
                    </div>
                    <div className="flex-1">
                      <h3 className="font-mono text-lg font-bold mb-2 text-[#78C4D4]">{method.title}</h3>
                      <p className="font-mono text-xs text-white/70 leading-relaxed">{'// '}{method.description}</p>
                    </div>
                  </div>

                  {/* Progress indicator */}
                  <div className="absolute bottom-0 left-0 right-0 h-1 bg-[#333]">
                    <motion.div
                      className="h-full bg-[#00FF96]"
                      initial={{ width: 0 }}
                      whileInView={{ width: `${((index + 1) / methods.length) * 100}%` }}
                      viewport={{ once: true }}
                      transition={{ duration: 1, delay: 0.3 + index * 0.1 }}
                    />
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="relative py-24 px-6 md:px-12 lg:px-24 border-t border-[#333] bg-gradient-to-b from-black via-[#001a1a] to-black">
          <div className="container mx-auto max-w-4xl relative z-10">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-3xl md:text-5xl font-bold mb-6"
            >
              {'>'} あなたの課題を
              <br />
              <span className="text-[#00FF96]">研究テーマ</span>にしませんか？
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-sm text-white/70 mb-8"
            >
              {'// '}まずは無料相談から、実験を始めましょう。
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              <a href="/contact">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  animate={{
                    boxShadow: [
                      '0 0 20px rgba(239, 68, 68, 0.8)',
                      '0 0 40px rgba(239, 68, 68, 0.4)',
                      '0 0 20px rgba(239, 68, 68, 0.8)'
                    ]
                  }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                  className="font-mono text-sm px-10 py-5 bg-red-600 hover:bg-red-700 text-white font-bold uppercase tracking-wider border-2 border-red-500 relative overflow-hidden"
                >
                  <span className="relative z-10 flex items-center gap-2">
                    <span className="text-yellow-300">⚠</span>
                    {'>'} 無料で相談する
                    <span className="text-yellow-300">⚠</span>
                  </span>
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
                    animate={{ x: ['-100%', '200%'] }}
                    transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
                  />
                </motion.button>
              </a>
            </motion.div>

            <motion.div
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="flex gap-6 text-xs font-mono text-white/40 pt-6 flex-wrap"
            >
              <div>RESPONSE: 2営業日以内</div>
              <div>|</div>
              <div>NDA: 対応可能</div>
              <div>|</div>
              <div>CONSULTATION: 無料</div>
            </motion.div>
          </div>
        </section>

        {/* Corner Decorations */}
        <div className="fixed top-8 left-8 w-16 h-16 border-t-2 border-l-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed top-8 right-8 w-16 h-16 border-t-2 border-r-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed bottom-8 left-8 w-16 h-16 border-b-2 border-l-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed bottom-8 right-8 w-16 h-16 border-b-2 border-r-2 border-[#78C4D4] opacity-30 pointer-events-none" />
      </main>

      <Footer />
    </>
  )
}
