// Generated by ClaudeCode - Systems Page (Cyber Style)
'use client'

import { motion } from 'framer-motion'
import { useState } from 'react'
import LoadingScreen from '@/components/LoadingScreen'
import Header from '@/components/sections/Header'
import Footer from '@/components/sections/Footer'

export default function SystemsPage() {
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null)

  return (
    <>
      <LoadingScreen />
      <SystemsPageContent expandedFaq={expandedFaq} setExpandedFaq={setExpandedFaq} />
    </>
  )
}

function SystemsPageContent({ expandedFaq, setExpandedFaq }: { expandedFaq: number | null; setExpandedFaq: (index: number | null) => void }) {
  const systems = [
    {
      name: '請求書管理システム',
      icon: '[INV]',
      description: 'AI-OCRとZapierを活用した請求書の自動処理・管理システム',
      features: [
        'PDF/画像から自動データ抽出',
        'Google Sheets自動記録',
        '支払期限アラート通知',
        '承認ワークフロー',
      ],
      price: '初期費用 ¥150,000〜 / 月額 ¥5,000〜',
    },
    {
      name: '契約書管理システム',
      icon: '[CON]',
      description: '契約書の電子化・一元管理・検索システム',
      features: [
        '全文検索機能',
        '期限管理・アラート',
        '承認フロー機能',
        'Box/OneDrive連携',
      ],
      price: '初期費用 ¥180,000〜 / 月額 ¥6,000〜',
    },
    {
      name: '営業支援システム',
      icon: '[CRM]',
      description: 'Airtableベースの営業活動管理・分析システム',
      features: [
        '案件管理・進捗可視化',
        '顧客情報一元管理',
        'Slack連携通知',
        'レポート自動生成',
      ],
      price: '初期費用 ¥200,000〜 / 月額 ¥8,000〜',
    },
    {
      name: '勤怠管理システム',
      icon: '[ATT]',
      description: 'Google Apps Scriptによる勤怠記録・集計システム',
      features: [
        'LINE/Slack打刻',
        '自動集計・給与計算',
        '有給管理',
        'CSV出力',
      ],
      price: '初期費用 ¥120,000〜 / 月額 ¥4,000〜',
    },
  ]

  const pricingPlans = [
    {
      name: 'Lite',
      setupPrice: '¥80,000〜',
      monthlyPrice: '¥3,000〜',
      features: [
        '既存ツール連携',
        'スプレッドシート自動化',
        '基本レポート機能',
        'メールサポート',
      ],
    },
    {
      name: 'Business',
      setupPrice: '¥200,000〜',
      monthlyPrice: '¥5,000〜',
      features: [
        'カスタムワークフロー',
        'AI連携（OCR/要約）',
        'ダッシュボード構築',
        'チャットサポート',
        'データ分析支援',
      ],
      recommended: true,
    },
    {
      name: 'Custom',
      setupPrice: '¥400,000〜',
      monthlyPrice: '¥10,000〜',
      features: [
        'フルカスタム開発',
        '複数システム統合',
        'API開発',
        '専任担当者',
        'オンサイト対応可',
      ],
    },
  ]

  const faqs = [
    {
      question: 'カスタマイズは可能ですか？',
      answer: 'はい、貴社の業務フローに合わせて柔軟にカスタマイズ可能です。初期ヒアリングで詳細をお伺いし、最適な仕様をご提案いたします。',
    },
    {
      question: '導入までどのくらいかかりますか？',
      answer: '規模にもよりますが、通常2〜4週間程度で導入可能です。プロトタイプは1週間程度で確認いただけます。',
    },
    {
      question: '既存システムとの連携は可能ですか？',
      answer: 'はい、API連携により既存のSaaS（Slack、Salesforce、kintone等）との統合が可能です。',
    },
    {
      question: 'サポート体制はどうなっていますか？',
      answer: 'チャット/メールでの問い合わせ対応、バグ修正、機能改善を月額料金内で対応いたします。緊急時は電話対応も可能です。',
    },
    {
      question: 'データのセキュリティは大丈夫ですか？',
      answer: 'データは暗号化され、Google Cloud / AWSなどの信頼性の高いプラットフォーム上で管理されます。秘密保持契約の締結も可能です。',
    },
    {
      question: '月額料金に含まれるものは何ですか？',
      answer: 'システムの保守・運用、バグ修正、セキュリティアップデート、チャットサポートが含まれます。大規模な機能追加は別途お見積りとなります。',
    },
    {
      question: '最低契約期間はありますか？',
      answer: '基本的に6ヶ月からの契約となります。システムの安定稼働と投資回収を考慮した期間設定となっております。',
    },
    {
      question: 'トライアル期間はありますか？',
      answer: 'はい、1ヶ月間の無料トライアル（プロトタイプ版）をご利用いただけます。実際の業務で試した上で本導入をご判断ください。',
    },
  ]

  return (
    <>
      <Header />

      <main className="min-h-screen bg-black text-white relative">
        {/* Background Grid Pattern */}
        <div className="fixed inset-0 opacity-10 pointer-events-none">
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="systems-grid" width="40" height="40" patternUnits="userSpaceOnUse">
                <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#systems-grid)" />
          </svg>
        </div>

        {/* Scan Line Effect */}
        <motion.div
          className="fixed inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/5 to-transparent pointer-events-none"
          animate={{ y: ['-100%', '200%'] }}
          transition={{ duration: 8, repeat: Infinity, ease: 'linear' }}
        />

        {/* Hero Section */}
        <section className="relative pt-32 pb-16 px-6 md:px-12 lg:px-24">
          <div className="container mx-auto max-w-7xl relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              {/* Kicker */}
              <div className="font-mono text-xs text-[#78C4D4] border-l-4 border-[#78C4D4] pl-4 mb-8 uppercase tracking-widest">
                [SYSTEMS_LAB] SOLUTION_CATALOG
              </div>

              {/* Title */}
              <h1 className="font-mono text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-white tracking-tight">
                {'>'} BUSINESS_
                <span className="text-[#00FF96]">AUTOMATION</span>
              </h1>

              {/* Description */}
              <p className="text-white/70 text-sm md:text-base max-w-3xl font-mono leading-relaxed">
                {'// '}実証済みの業務システムで効率を劇的に改善
                <br />
                {'// '}低コストで素早く導入、確実な成果を実現
              </p>

              {/* Stats Bar */}
              <div className="mt-8 flex flex-wrap gap-6 font-mono text-xs">
                <div className="flex items-center space-x-2">
                  <motion.span
                    className="text-[#00FF96]"
                    animate={{ opacity: [1, 0.5, 1] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  >
                    ●
                  </motion.span>
                  <span className="text-white/60">SYSTEMS: <span className="text-[#00FF96]">05_TYPES</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#78C4D4]">●</span>
                  <span className="text-white/60">DEPLOYMENT: <span className="text-[#78C4D4]">2-4_WEEKS</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#00C896]">●</span>
                  <span className="text-white/60">STATUS: <span className="text-[#00C896]">ACTIVE</span></span>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Systems List */}
        <section className="relative py-20 px-6 md:px-12 lg:px-24 border-t border-[#333]">
          <div className="container mx-auto max-w-6xl">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest border-l-4 border-[#78C4D4] pl-4 mb-8 inline-block"
            >
              [SECTION_02] AVAILABLE_SYSTEMS
            </motion.div>

            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-3xl md:text-4xl lg:text-5xl font-bold mb-6"
            >
              {'<'}SYSTEMS{'>'} <span className="text-[#00FF96]">{'//'} 導入可能なシステム</span>
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="font-mono text-sm text-white/70 mb-12"
            >
              {'> '}すぐに導入できる、実証済みの業務システム
            </motion.p>

            <div className="grid md:grid-cols-2 gap-6">
              {systems.map((system, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="bg-black border border-[#333] p-6 relative overflow-hidden group hover:border-[#78C4D4] transition-all duration-300"
                >
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-b from-[#78C4D4]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"
                  />

                  <div className="flex items-start gap-4 mb-4 relative z-10">
                    <div className="font-mono text-4xl font-bold text-[#00FF96]">{system.icon}</div>
                    <div className="flex-1">
                      <h3 className="font-mono text-xl font-bold mb-2 text-[#78C4D4]">{system.name}</h3>
                      <p className="font-mono text-xs text-white/70 leading-relaxed">{'// '}{system.description}</p>
                    </div>
                  </div>

                  <div className="border-t border-[#333] pt-4 mb-4 relative z-10">
                    <div className="font-mono text-xs text-[#00FF96] mb-3">[FEATURES]</div>
                    <ul className="space-y-2">
                      {system.features.map((feature, i) => (
                        <li key={i} className="font-mono text-xs text-white/60 flex items-center gap-3">
                          <span className="w-1 h-1 bg-[#00FF96] rounded-full flex-shrink-0" />
                          {feature}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="border-t border-[#333] pt-4 relative z-10">
                    <div className="font-mono text-sm text-[#00FF96] font-bold">{system.price}</div>
                  </div>

                  {/* Corner decorations */}
                  <div className="absolute top-0 right-0 w-4 h-4 border-t border-r border-[#78C4D4] opacity-30" />
                  <div className="absolute bottom-0 left-0 w-4 h-4 border-b border-l border-[#78C4D4] opacity-30" />
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Pricing Plans */}
        <section className="relative py-20 px-6 md:px-12 lg:px-24 border-t border-[#333]">
          <div className="container mx-auto max-w-6xl">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest border-l-4 border-[#78C4D4] pl-4 mb-8 inline-block"
            >
              [SECTION_03] PRICING
            </motion.div>

            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-3xl md:text-4xl lg:text-5xl font-bold mb-6"
            >
              {'<'}PLANS{'>'} <span className="text-[#00FF96]">{'//'} 料金プラン</span>
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="font-mono text-sm text-white/70 mb-12"
            >
              {'> '}規模や要件に応じて、3つのプランから選択できます。
            </motion.p>

            <div className="grid md:grid-cols-3 gap-6">
              {pricingPlans.map((plan, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className={`bg-black border-2 p-6 relative overflow-hidden group transition-all duration-300 ${
                    plan.recommended ? 'border-[#00FF96]' : 'border-[#333] hover:border-[#78C4D4]'
                  }`}
                >
                  {plan.recommended && (
                    <div className="absolute -top-3 left-1/2 transform -translate-x-1/2 bg-[#00FF96] text-black font-mono text-xs font-bold px-4 py-1 border-2 border-[#00C896]">
                      [RECOMMENDED]
                    </div>
                  )}

                  <motion.div
                    className="absolute inset-0 bg-gradient-to-b from-[#78C4D4]/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"
                  />

                  <h3 className="font-mono text-2xl font-bold mb-4 text-[#78C4D4] relative z-10">{plan.name}</h3>

                  <div className="mb-6 relative z-10">
                    <div className="font-mono text-xs text-white/50 mb-1">[SETUP_COST]</div>
                    <div className="font-mono text-2xl font-bold text-[#00FF96] mb-3">{plan.setupPrice}</div>
                    <div className="font-mono text-xs text-white/50 mb-1">[MONTHLY]</div>
                    <div className="font-mono text-2xl font-bold text-[#00FF96]">{plan.monthlyPrice}</div>
                  </div>

                  <div className="border-t border-[#333] pt-4 relative z-10">
                    <ul className="space-y-3">
                      {plan.features.map((feature, i) => (
                        <li key={i} className="font-mono text-xs text-white/70 flex items-start gap-2">
                          <span className="text-[#00FF96] font-bold mt-0.5">✓</span>
                          <span>{feature}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Corner decorations */}
                  <div className="absolute top-0 left-0 w-4 h-4 border-t border-l border-[#78C4D4] opacity-30" />
                  <div className="absolute bottom-0 right-0 w-4 h-4 border-b border-r border-[#78C4D4] opacity-30" />
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ */}
        <section className="relative py-20 px-6 md:px-12 lg:px-24 border-t border-[#333]">
          <div className="container mx-auto max-w-6xl">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-xs text-[#78C4D4] uppercase tracking-widest border-l-4 border-[#78C4D4] pl-4 mb-8 inline-block"
            >
              [SECTION_04] FAQ
            </motion.div>

            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-3xl md:text-4xl lg:text-5xl font-bold mb-6"
            >
              {'<'}FAQ{'>'} <span className="text-[#00FF96]">{'//'} よくある質問</span>
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="font-mono text-sm text-white/70 mb-12"
            >
              {'> '}システム導入に関するよくある質問にお答えします。
            </motion.p>

            <div className="max-w-4xl mx-auto space-y-3">
              {faqs.map((faq, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: index * 0.05 }}
                  className="bg-black border border-[#333] overflow-hidden"
                >
                  <button
                    onClick={() => setExpandedFaq(expandedFaq === index ? null : index)}
                    className="w-full text-left p-6 hover:bg-[#78C4D4]/5 transition-colors"
                  >
                    <div className="flex items-center justify-between gap-4">
                      <div className="flex items-start gap-3 flex-1">
                        <span className="text-[#00FF96] font-mono font-bold flex-shrink-0 text-xs">
                          [Q{String(index + 1).padStart(2, '0')}]
                        </span>
                        <h3 className="font-mono text-base font-bold text-[#78C4D4]">{faq.question}</h3>
                      </div>
                      <motion.div
                        animate={{ rotate: expandedFaq === index ? 180 : 0 }}
                        transition={{ duration: 0.3 }}
                        className="text-[#78C4D4] text-xl flex-shrink-0"
                      >
                        ▼
                      </motion.div>
                    </div>
                  </button>

                  {expandedFaq === index && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      transition={{ duration: 0.3 }}
                      className="px-6 pb-6 border-t border-[#333] pt-4"
                    >
                      <p className="font-mono text-xs text-white/70 leading-relaxed pl-8">{'// '}{faq.answer}</p>
                    </motion.div>
                  )}
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="relative py-24 px-6 md:px-12 lg:px-24 border-t border-[#333] bg-gradient-to-b from-black via-[#001a1a] to-black">
          <div className="container mx-auto max-w-4xl relative z-10">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="font-mono text-3xl md:text-5xl font-bold mb-6"
            >
              {'>'} あなたの業務に
              <br />
              <span className="text-[#00FF96]">最適なシステム</span>をご提案します
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="font-mono text-sm text-white/70 mb-8"
            >
              {'// '}まずは無料相談で、課題をお聞かせください。
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              <a href="/contact">
                <motion.button
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  animate={{
                    boxShadow: [
                      '0 0 20px rgba(239, 68, 68, 0.8)',
                      '0 0 40px rgba(239, 68, 68, 0.4)',
                      '0 0 20px rgba(239, 68, 68, 0.8)'
                    ]
                  }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                  className="font-mono text-sm px-10 py-5 bg-red-600 hover:bg-red-700 text-white font-bold uppercase tracking-wider border-2 border-red-500 relative overflow-hidden"
                >
                  <span className="relative z-10 flex items-center gap-2">
                    <span className="text-yellow-300">⚠</span>
                    {'>'} 無料で相談する
                    <span className="text-yellow-300">⚠</span>
                  </span>
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
                    animate={{ x: ['-100%', '200%'] }}
                    transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
                  />
                </motion.button>
              </a>
            </motion.div>

            <motion.div
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.3 }}
              className="flex gap-6 text-xs font-mono text-white/40 pt-6 flex-wrap"
            >
              <div>RESPONSE: 2営業日以内</div>
              <div>|</div>
              <div>NDA: 対応可能</div>
              <div>|</div>
              <div>TRIAL: 1ヶ月無料</div>
            </motion.div>
          </div>
        </section>

        {/* Corner Decorations */}
        <div className="fixed top-8 left-8 w-16 h-16 border-t-2 border-l-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed top-8 right-8 w-16 h-16 border-t-2 border-r-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed bottom-8 left-8 w-16 h-16 border-b-2 border-l-2 border-[#78C4D4] opacity-30 pointer-events-none" />
        <div className="fixed bottom-8 right-8 w-16 h-16 border-b-2 border-r-2 border-[#78C4D4] opacity-30 pointer-events-none" />
      </main>

      <Footer />
    </>
  )
}
