// Generated by ClaudeCode - 研究成果一覧ページ (Cyber/Control Panel Style)
'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import LoadingScreen from '@/components/LoadingScreen'
import Header from '@/components/sections/Header'
import Footer from '@/components/sections/Footer'

const allWorks = [
  {
    id: 'inventory-automation',
    caseNumber: '01',
    title: '在庫管理自動化システム',
    category: '業務システム',
    description: '発注業務を完全自動化。在庫数をリアルタイム監視し、閾値を下回ると自動発注メールを送信。手作業による発注ミスを完全に排除。',
    tags: ['Google Sheets API', 'Zapier', 'Gmail API'],
    client: 'EC事業者',
    duration: '2週間',
    result: '発注ミス ゼロ化',
    status: 'SUCCESS',
  },
  {
    id: 'customer-inquiry-bot',
    caseNumber: '02',
    title: 'AI問い合わせ自動応答システム',
    category: 'AI連携',
    description: 'ChatGPT APIとSlackを連携し、顧客からの問い合わせに24時間自動応答。FAQデータベースを学習させ、一次対応を完全自動化。',
    tags: ['ChatGPT API', 'Slack Bot', 'Python'],
    client: 'SaaS企業',
    duration: '3週間',
    result: '応答時間 90%短縮',
    status: 'SUCCESS',
  },
  {
    id: 'document-ocr-system',
    caseNumber: '03',
    title: '書類自動データ化システム',
    category: 'AI連携',
    description: 'OCR技術で紙の請求書や契約書をデータ化し、自動でスプレッドシートに転記。手入力作業を完全撤廃し、入力精度も大幅向上。',
    tags: ['AI-OCR', 'Google Drive API', 'Apps Script'],
    client: '不動産管理会社',
    duration: '1ヶ月',
    result: '入力工数 70時間/月 削減',
    status: 'SUCCESS',
  },
  {
    id: 'schedule-coordination',
    caseNumber: '04',
    title: '日程調整自動化ツール',
    category: '業務システム',
    description: '複数人の空き時間を自動抽出し、最適な会議日時を提案。Googleカレンダーと連携し、日程調整の往復メールを完全排除。',
    tags: ['Google Calendar API', 'Node.js', 'Webhook'],
    client: 'コンサルティング会社',
    duration: '2週間',
    result: '調整時間 85%削減',
    status: 'SUCCESS',
  },
  {
    id: 'sales-report-automation',
    caseNumber: '05',
    title: '営業レポート自動生成システム',
    category: '業務システム',
    description: '各種SaaSツールから売上データを自動収集し、週次・月次レポートを自動生成。経営判断に必要なダッシュボードをリアルタイム更新。',
    tags: ['Looker Studio', 'BigQuery', 'API連携'],
    client: '営業代行企業',
    duration: '3週間',
    result: 'レポート作成時間 95%削減',
    status: 'SUCCESS',
  },
  {
    id: 'employee-onboarding',
    caseNumber: '06',
    title: '入社手続き自動化システム',
    category: '業務システム',
    description: '入社時のアカウント発行、設備手配、研修予約を自動化。人事担当者の作業負荷を削減し、新入社員の初日からスムーズな業務開始を実現。',
    tags: ['Airtable', 'Slack API', 'Make.com'],
    client: 'IT企業',
    duration: '1ヶ月',
    result: '入社対応時間 60%削減',
    status: 'SUCCESS',
  },
]

export default function WorksPage() {
  return (
    <>
      <LoadingScreen />
      <Header />
      <main className="min-h-screen bg-black text-white">
        {/* Background Grid Pattern */}
        <div className="fixed inset-0 opacity-10 pointer-events-none">
          <svg width="100%" height="100%" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <pattern id="work-grid" width="40" height="40" patternUnits="userSpaceOnUse">
                <path d="M 40 0 L 0 0 0 40" fill="none" stroke="#78C4D4" strokeWidth="0.5"/>
              </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#work-grid)" />
          </svg>
        </div>

        {/* Hero Section */}
        <section className="relative pt-32 pb-16 px-6 md:px-12 lg:px-24">
          <div className="container mx-auto max-w-7xl relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              {/* Kicker */}
              <div className="font-mono text-xs text-[#78C4D4] border-l-4 border-[#78C4D4] pl-4 mb-8 uppercase tracking-widest">
                [RESEARCH_RESULTS] EXPERIMENT_DATABASE
              </div>

              {/* Title */}
              <h1 className="font-mono text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-white tracking-tight">
                {'>'} RESEARCH_
                <span className="text-[#00FF96]">ARCHIVE</span>
              </h1>

              {/* Description */}
              <p className="text-white/70 text-sm md:text-base max-w-3xl font-mono leading-relaxed">
                {'// '}実験を重ねて蓄積された研究データベース
                <br />
                {'// '}小規模プロトタイプから始めて、確実な成果を生み出すアプローチ
              </p>

              {/* Stats Bar */}
              <div className="mt-8 flex flex-wrap gap-6 font-mono text-xs">
                <div className="flex items-center space-x-2">
                  <motion.span
                    className="text-[#00FF96]"
                    animate={{ opacity: [1, 0.5, 1] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  >
                    ●
                  </motion.span>
                  <span className="text-white/60">TOTAL_PROJECTS: <span className="text-[#00FF96]">06</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#78C4D4]">●</span>
                  <span className="text-white/60">SUCCESS_RATE: <span className="text-[#78C4D4]">100%</span></span>
                </div>
                <div className="flex items-center space-x-2">
                  <span className="text-[#00C896]">●</span>
                  <span className="text-white/60">STATUS: <span className="text-[#00C896]">ACTIVE</span></span>
                </div>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Works Grid */}
        <section className="relative py-16 px-6 md:px-12 lg:px-24">
          <div className="container mx-auto max-w-7xl relative z-10">
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {allWorks.map((work, index) => (
                <motion.div
                  key={work.id}
                  initial={{ opacity: 0, y: 30 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.1 + index * 0.1 }}
                  className="bg-black border border-[#333] hover:border-[#78C4D4] transition-all duration-300 relative overflow-hidden group"
                >
                  {/* Scan Line Effect */}
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-b from-transparent via-[#78C4D4]/10 to-transparent h-[200%] pointer-events-none"
                    animate={{ y: ['-100%', '100%'] }}
                    transition={{ duration: 3, repeat: Infinity, ease: 'linear' }}
                  />

                  {/* Header Bar */}
                  <div className="bg-[#111] border-b border-[#333] px-4 py-3 font-mono text-xs">
                    <div className="flex items-center justify-between">
                      <span className="text-[#00FF96]">[CASE_{work.caseNumber}]</span>
                      <span className="text-white/40 uppercase">{work.category}</span>
                    </div>
                  </div>

                  {/* Content */}
                  <div className="p-6 relative z-10">
                    {/* Title */}
                    <h3 className="font-mono text-xl font-bold text-white mb-4 group-hover:text-[#78C4D4] transition-colors">
                      {'> '}{work.title}
                    </h3>

                    {/* Description */}
                    <p className="text-white/60 text-sm leading-relaxed mb-6 min-h-[6rem]">
                      {work.description}
                    </p>

                    {/* Info Grid */}
                    <div className="space-y-3 mb-6 font-mono text-xs">
                      <div className="flex justify-between border-b border-[#333] pb-2">
                        <span className="text-white/40">CLIENT:</span>
                        <span className="text-white/80">{work.client}</span>
                      </div>
                      <div className="flex justify-between border-b border-[#333] pb-2">
                        <span className="text-white/40">DURATION:</span>
                        <span className="text-white/80">{work.duration}</span>
                      </div>
                      <div className="flex justify-between border-b border-[#333] pb-2">
                        <span className="text-white/40">RESULT:</span>
                        <span className="text-[#00FF96]">{work.result}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-white/40">STATUS:</span>
                        <span className="text-[#00FF96] flex items-center space-x-1">
                          <motion.span
                            animate={{ opacity: [1, 0.3, 1] }}
                            transition={{ duration: 1.5, repeat: Infinity }}
                          >
                            ●
                          </motion.span>
                          <span>{work.status}</span>
                        </span>
                      </div>
                    </div>

                    {/* Tags */}
                    <div className="flex flex-wrap gap-2">
                      {work.tags.map((tag, tagIndex) => (
                        <span
                          key={tagIndex}
                          className="bg-[#111] border border-[#333] px-3 py-1 text-[10px] font-mono text-[#78C4D4] uppercase tracking-wider"
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Corner Decoration */}
                  <div className="absolute top-0 right-0 w-8 h-8 border-t-2 border-r-2 border-[#78C4D4] opacity-50" />
                  <div className="absolute bottom-0 left-0 w-8 h-8 border-b-2 border-l-2 border-[#78C4D4] opacity-50" />
                </motion.div>
              ))}
            </div>

            {/* CTA Panel */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.8 }}
              className="mt-16 bg-black border-2 border-[#78C4D4] p-8 md:p-12 relative overflow-hidden"
            >
              {/* Background Glow */}
              <div className="absolute inset-0 bg-gradient-to-br from-[#78C4D4]/5 via-transparent to-[#00FF96]/5 pointer-events-none" />

              <div className="relative z-10 text-center">
                {/* Kicker */}
                <div className="font-mono text-xs text-[#78C4D4] mb-4 uppercase tracking-widest">
                  [INQUIRY_SYSTEM] READY
                </div>

                {/* Title */}
                <h3 className="font-mono text-2xl md:text-3xl font-bold mb-4 text-white">
                  {'>'} START_YOUR_
                  <span className="text-[#00FF96]">EXPERIMENT</span>
                </h3>

                {/* Description */}
                <p className="text-white/70 text-sm mb-8 max-w-2xl mx-auto font-mono">
                  {'// '}どんな小さな課題でも、まずはご相談ください
                  <br />
                  {'// '}実験的なアプローチで、最適な解決策を見つけます
                </p>

                {/* CTA Button */}
                <Link href="/contact">
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    animate={{
                      boxShadow: [
                        '0 0 20px rgba(239, 68, 68, 0.8)',
                        '0 0 40px rgba(239, 68, 68, 0.4)',
                        '0 0 20px rgba(239, 68, 68, 0.8)'
                      ]
                    }}
                    transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                    className="font-mono text-sm px-8 py-4 bg-red-600 hover:bg-red-700 text-white font-bold uppercase tracking-wider border-2 border-red-500 relative overflow-hidden"
                  >
                    <span className="relative z-10 flex items-center gap-2">
                      <span className="text-yellow-300">⚠</span>
                      {'>'} 無料相談を開始
                      <span className="text-yellow-300">⚠</span>
                    </span>
                    <motion.div
                      className="absolute inset-0 bg-gradient-to-r from-transparent via-red-400/30 to-transparent"
                      animate={{ x: ['-100%', '200%'] }}
                      transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
                    />
                  </motion.button>
                </Link>

                {/* Stats */}
                <div className="mt-8 flex justify-center gap-8 font-mono text-xs text-white/60">
                  <div>RESPONSE: <span className="text-[#78C4D4]">2営業日以内</span></div>
                  <div>NDA: <span className="text-[#00FF96]">対応可能</span></div>
                </div>
              </div>

              {/* Corner Brackets */}
              <div className="absolute top-4 left-4 w-12 h-12 border-t-2 border-l-2 border-[#78C4D4]" />
              <div className="absolute top-4 right-4 w-12 h-12 border-t-2 border-r-2 border-[#78C4D4]" />
              <div className="absolute bottom-4 left-4 w-12 h-12 border-b-2 border-l-2 border-[#78C4D4]" />
              <div className="absolute bottom-4 right-4 w-12 h-12 border-b-2 border-r-2 border-[#78C4D4]" />
            </motion.div>
          </div>
        </section>
      </main>

      <Footer />
    </>
  )
}
